# Generated by Django 4.2.8 on 2025-12-20 15:03

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_link',
            field=models.CharField(blank=True, help_text='Ссылка для активации аккаунта', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Активирован ли аккаунт через email'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор токена', max_length=36, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(help_text='Refresh токен (JWT строка)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания токена')),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит токен', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'db_table': 'tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
