# Generated by Django 4.2.8 on 2025-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, help_text='Код активации (6 цифр) для подтверждения email', max_length=6, null=True),
        ),
    ]
