# Generated by Django 4.2.8 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_notifications',
            field=models.BooleanField(default=False, verbose_name='Маркетинговые уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о заказах'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_pet_types',
            field=models.JSONField(blank=True, default=list, help_text='Список предпочитаемых типов питомцев для персонализации', verbose_name='Предпочитаемые типы питомцев'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
