# Generated by Django 5.1.5 on 2026-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_password_reset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_created_at',
            field=models.DateTimeField(blank=True, help_text='Время создания кода активации для проверки срока действия', null=True),
        ),
    ]
