# Generated by Django 5.1.5 on 2026-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('course_creator', 'Создатель курсов'), ('admin', 'Администратор')], db_index=True, default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
