# Generated by Django 4.2.8 on 2026-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_user_bio_user_city_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_created_at',
            field=models.DateTimeField(blank=True, help_text='Время создания кода активации/восстановления для проверки срока действия', null=True),
        ),
    ]
