# Generated by Django 4.2.8 on 2026-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, help_text='Код восстановления пароля (6 цифр)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, help_text='Время создания кода восстановления пароля для проверки срока действия', null=True),
        ),
    ]