# Generated by Django 5.1.5 on 2026-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки ввода')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'OTP по телефону',
                'verbose_name_plural': 'OTP по телефону',
                'db_table': 'phone_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
