# Generated by Django 5.1.5 on 2026-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_email_verified_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('course_creator', 'Создатель курсов'), ('supplier_manager', 'Менеджер поставщика'), ('supplier_editor', 'Редактор поставщика'), ('supplier_analyst', 'Аналитик поставщика'), ('admin', 'Администратор')], db_index=True, default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
