# Generated by Django 5.1.5 on 2026-06-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0032_suppliercatalogsynclog_supplierproductsubmission_and_more'),
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccessRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_role', models.CharField(choices=[('supplier', 'Поставщик корма'), ('course_specialist', 'Специалист по курсам')], max_length=20, verbose_name='Запрашиваемый доступ')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('review_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина решения')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('granted_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='pets.supplier', verbose_name='Выданный поставщик')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на партнёрский доступ',
                'verbose_name_plural': 'Заявки на партнёрский доступ',
                'db_table': 'partner_access_requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'requested_role'), name='uniq_pending_partner_request_per_user_role')],
            },
        ),
    ]
