# Generated by Django 4.2.8 on 2025-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('basics', 'Основы'), ('training', 'Дрессировка'), ('care', 'Уход'), ('health', 'Здоровье'), ('nutrition', 'Питание'), ('behavior', 'Поведение'), ('specialized', 'Специализированные'), ('entertainment', 'Развлечения')], db_index=True, default='basics', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='format_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('interactive', 'Интерактивный'), ('mixed', 'Смешанный'), ('webinar', 'Вебинар'), ('workshop', 'Мастер-класс')], db_index=True, default='video', max_length=15, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], db_index=True, default='beginner', max_length=15, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('first_steps', 'Первые шаги'), ('socialization', 'Социализация'), ('toilet_training', 'Приучение к туалету'), ('obedience', 'Послушание'), ('tricks', 'Трюки'), ('sports', 'Спортивная'), ('service', 'Служебная'), ('grooming', 'Груминг'), ('hygiene', 'Гигиена'), ('coat_care', 'Уход за шерстью'), ('prevention', 'Профилактика'), ('first_aid', 'Первая помощь'), ('vaccination', 'Вакцинация'), ('feeding_basics', 'Основы кормления'), ('diet_selection', 'Выбор рациона'), ('natural_feeding', 'Натуральное питание'), ('behavior_problems', 'Проблемы поведения'), ('aggression', 'Агрессия'), ('anxiety', 'Тревожность'), ('breeding', 'Разведение'), ('shows', 'Выставки'), ('therapy', 'Канистерапия'), ('games', 'Игры'), ('toys', 'Игрушки'), ('activities', 'Активности')], db_index=True, max_length=30, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['pet_type', 'category'], name='courses_pet_typ_35e40e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['pet_type', 'category', 'level'], name='courses_pet_typ_4481d8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'level'], name='courses_categor_d7f094_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='courses_price_56bbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['format_type'], name='courses_format__f13f84_idx'),
        ),
    ]
