# Generated by Django 4.2.8 on 2025-12-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0003_alter_pet_breed_alter_pet_created_at_and_more'),
        ('training', '0003_course_additional_images_course_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Питомец, для которого приобретён курс (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course', 'pet')},
        ),
    ]
