# Generated by Django 4.2.8 on 2026-01-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_skip_coursepage_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
