# Generated by Django 4.2.8 on 2026-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_add_course_module_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='completed_pages_ids',
            field=models.JSONField(blank=True, default=list, help_text='Список ID завершённых CoursePage для отслеживания прогресса', verbose_name='ID завершённых страниц'),
        ),
    ]
