# Generated by Django 4.2.8 on 2026-02-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_add_completed_pages_ids'),
    ]

    operations = [
        # SeparateDatabaseAndState: ограничение unique_together для content_blocks
        # в БД отсутствует (таблица создана в 0016 через raw SQL без него),
        # поэтому обновляем только состояние миграций, без операций с БД.
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ограничения нет — ничего не дропаем
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='contentblock',
                    unique_together=set(),
                ),
            ],
        ),
    ]
