# Generated by Django 5.1.5 on 2026-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_alter_coursepage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Собак'), ('cat', 'Кошек'), ('all', 'Все')], default='all', max_length=10, verbose_name='Тип животного'),
        ),
    ]
