# Generated by Django 4.2.8 on 2025-12-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(help_text='Длительность в минутах', verbose_name='Длительность')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL обложки')),
                ('pet_type', models.CharField(choices=[('dog', 'Для собак'), ('cat', 'Для кошек'), ('all', 'Для всех')], default='all', max_length=10, verbose_name='Тип животного')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Процент прохождения (0-100)', verbose_name='Прогресс')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='training.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Курс пользователя',
                'verbose_name_plural': 'Курсы пользователей',
                'db_table': 'user_courses',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
