# Generated by Django 4.2.8 on 2025-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_course_category_course_format_type_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='Массив URL дополнительных изображений курса', verbose_name='Дополнительные изображения'),
        ),
        migrations.AddField(
            model_name='course',
            name='completion_time',
            field=models.CharField(blank=True, help_text='Оценка времени для прохождения курса (например, "2-3 недели", "1 месяц")', max_length=100, null=True, verbose_name='Время прохождения'),
        ),
        migrations.AddField(
            model_name='course',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='format_details',
            field=models.TextField(blank=True, help_text='Подробное описание формата обучения (количество видео, материалов и т.д.)', null=True, verbose_name='Детали формата'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография инструктора'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя инструктора'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество уроков'),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество материалов'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='Что необходимо знать или иметь перед началом курса', null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество видео'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Список навыков и знаний, которые получит пользователь', null=True, verbose_name='Чему вы научитесь'),
        ),
    ]
