# Generated by Django 4.2.8 on 2025-12-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_usercourse_unique_together_usercourse_pet_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Recreate courses table with correct schema matching Django model
            DROP TABLE IF EXISTS courses CASCADE;

            CREATE TABLE courses (
                id serial NOT NULL PRIMARY KEY,
                title varchar(200) NOT NULL,
                description text NOT NULL,
                duration integer NOT NULL,
                price numeric(10,2) NOT NULL,
                image_url varchar(200) NULL,
                pet_type varchar(10) NOT NULL,
                category varchar(20) NOT NULL,
                subcategory varchar(30) NULL,
                level varchar(15) NOT NULL,
                format_type varchar(15) NOT NULL,
                detailed_description text NULL,
                what_you_will_learn text NULL,
                format_details text NULL,
                completion_time varchar(100) NULL,
                lessons_count integer NOT NULL DEFAULT 0,
                videos_count integer NOT NULL DEFAULT 0,
                materials_count integer NOT NULL DEFAULT 0,
                instructor_name varchar(200) NULL,
                instructor_bio text NULL,
                requirements text NULL,
                additional_images jsonb NOT NULL DEFAULT '[]'::jsonb,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );

            -- Create indexes
            CREATE INDEX courses_pet_type_category_idx ON courses (pet_type, category);
            CREATE INDEX courses_pet_type_category_level_idx ON courses (pet_type, category, level);
            CREATE INDEX courses_category_level_idx ON courses (category, level);
            CREATE INDEX courses_price_idx ON courses (price);
            CREATE INDEX courses_format_type_idx ON courses (format_type);
            """,
            reverse_sql="""
            -- Reverse migration: drop table
            DROP TABLE IF EXISTS courses CASCADE;
            """
        ),
    ]
