# Generated by Django 4.2.8 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20251224_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
