# Generated by Django 4.2.8 on 2025-12-25 17:27

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_behavior_type_pet_behavioral_problems_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_course_order_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор комментария', max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('attachments', models.JSONField(default=list, help_text='Список URL вложений (фото, видео питомца и т.д.)', verbose_name='Вложения')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитывается на основе связанных уроков', verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_count',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитывается на основе дополнительных материалов', verbose_name='Количество материалов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='videos_count',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически рассчитывается на основе видео-уроков', verbose_name='Количество видео'),
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор прогресса', max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('paused', 'Приостановлен')], default='not_started', max_length=15, verbose_name='Статус')),
                ('progress_percent', models.PositiveIntegerField(default=0, help_text='Процент завершения курса (0-100)', verbose_name='Процент выполнения')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Время в минутах, потраченное на курс', verbose_name='Общее время обучения')),
                ('completed_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Завершённых уроков')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training.course', verbose_name='Курс')),
                ('pet', models.ForeignKey(blank=True, help_text='Питомец, для которого проходит курс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_progress', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по курсу',
                'verbose_name_plural': 'Прогресс по курсам',
                'db_table': 'user_course_progress',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор оценки', max_length=36, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка от 1 до 5 звезд', verbose_name='Оценка')),
                ('review', models.TextField(blank=True, help_text='Текст отзыва о курсе', null=True, verbose_name='Отзыв')),
                ('is_approved', models.BooleanField(default=True, help_text='Прошел ли модерацию', verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='training.course', verbose_name='Курс')),
                ('pet', models.ForeignKey(blank=True, help_text='Питомец, в контексте которого дана оценка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка курса',
                'verbose_name_plural': 'Оценки курсов',
                'db_table': 'course_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content_type', models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('interactive', 'Интерактивный'), ('mixed', 'Смешанный'), ('webinar', 'Вебинар'), ('workshop', 'Мастер-класс')], default='video', max_length=20, verbose_name='Тип контента')),
                ('content', models.JSONField(default=dict, help_text='JSON структура с контентом урока (зависит от типа)', verbose_name='Контент урока')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Длительность в минутах', verbose_name='Длительность')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядковый номер урока в курсе', verbose_name='Порядок в курсе')),
                ('is_required', models.BooleanField(default=True, help_text='Должен ли быть пройден для завершения курса', verbose_name='Обязательный урок')),
                ('additional_materials', models.JSONField(default=list, help_text='Список дополнительных материалов (PDF, ссылки и т.д.)', verbose_name='Дополнительные материалы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор лайка', max_length=36, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(verbose_name='Лайк (True) или дизлайк (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='training.comment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк комментария',
                'verbose_name_plural': 'Лайки комментариев',
                'db_table': 'comment_likes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='training.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='training.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='training.comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор прогресса урока', max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('viewed', 'Просмотрен'), ('completed', 'Завершён'), ('skipped', 'Пропущен')], default='not_started', max_length=15, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Время в секундах, потраченное на урок', verbose_name='Время просмотра')),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Количество попыток выполнения интерактивных заданий', verbose_name='Количество попыток')),
                ('success_rate', models.PositiveIntegerField(default=0, help_text='Процент успешного выполнения (0-100)', verbose_name='Процент успешности')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='training.usercourseprogress', verbose_name='Прогресс курса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс по урокам',
                'db_table': 'user_lesson_progress',
                'ordering': ['lesson__order'],
                'indexes': [models.Index(fields=['course_progress', 'status'], name='user_lesson_course__52bfce_idx'), models.Index(fields=['lesson', 'status'], name='user_lesson_lesson__b56751_idx'), models.Index(fields=['status'], name='user_lesson_status_e6e258_idx')],
                'unique_together': {('course_progress', 'lesson')},
            },
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['user', 'status'], name='user_course_user_id_3935b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['course', 'status'], name='user_course_course__ecb804_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['pet', 'status'], name='user_course_pet_id_5774f2_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['status', 'progress_percent'], name='user_course_status_96b250_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course', 'pet')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['course', 'rating'], name='course_rati_course__9e682c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['course', '-created_at'], name='course_rati_course__e2d77d_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', '-created_at'], name='course_rati_user_id_2ca3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='course_rati_rating_d862ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'course', 'pet')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lessons_course__eb1bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='lessons_content_20a3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'is_like'], name='comment_lik_comment_cccc33_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', 'created_at'], name='comment_lik_user_id_40c748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['course', '-created_at'], name='comments_course__4c4dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['lesson', '-created_at'], name='comments_lesson__4be305_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_at'], name='comments_parent__b79743_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comments_user_id_a80af7_idx'),
        ),
    ]
