# Generated by Django 4.2.8 on 2025-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_comment_alter_course_lessons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='addresses_behavioral_problems',
            field=models.JSONField(blank=True, default=list, help_text='Список поведенческих проблем, которые решает курс', verbose_name='Решаемые поведенческие проблемы'),
        ),
        migrations.AddField(
            model_name='course',
            name='addresses_special_needs',
            field=models.JSONField(blank=True, default=list, help_text='Список особых потребностей, которые учитывает курс', verbose_name='Учитываемые особые потребности'),
        ),
        migrations.AddField(
            model_name='course',
            name='compatible_health_issues',
            field=models.JSONField(blank=True, default=list, help_text='Список проблем здоровья, с которыми совместим курс', verbose_name='Совместимые проблемы здоровья'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_training_experience',
            field=models.CharField(blank=True, choices=[('none', 'Без опыта'), ('basic', 'Базовый'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('professional', 'Профессиональный')], help_text='Минимальный уровень опыта дрессировки для прохождения курса', max_length=20, null=True, verbose_name='Минимальный опыт дрессировки'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_activity_levels',
            field=models.JSONField(blank=True, default=list, help_text='Список уровней активности, для которых подходит курс (low, medium, high)', verbose_name='Рекомендуемые уровни активности'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_behavior_types',
            field=models.JSONField(blank=True, default=list, help_text='Список типов поведения, для которых подходит курс (calm, active, aggressive, shy, playful)', verbose_name='Рекомендуемые типы поведения'),
        ),
        migrations.AddField(
            model_name='course',
            name='recommended_social_levels',
            field=models.JSONField(blank=True, default=list, help_text='Список уровней социализации, для которых подходит курс (home_only, street, social, mixed)', verbose_name='Рекомендуемые уровни социализации'),
        ),
        migrations.AddField(
            model_name='course',
            name='suitable_activities',
            field=models.JSONField(blank=True, default=list, help_text='Виды активностей питомца, для которых подходит курс', verbose_name='Подходящие активности'),
        ),
    ]
