# Generated by Django 4.2.8 on 2025-12-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_course_addresses_behavioral_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография инструктора (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя инструктора (устаревшее)'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('specialization', models.CharField(blank=True, help_text='Основная специализация (груминг, дрессировка и т.д.)', max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, help_text='Подробная информация об инструкторе', verbose_name='Биография')),
                ('photo_url', models.URLField(blank=True, help_text='URL фотографии инструктора', null=True, verbose_name='Фото')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Количество лет опыта работы', verbose_name='Опыт работы (лет)')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='Список достижений и наград', verbose_name='Достижения')),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='Сертификаты, дипломы, курсы повышения квалификации', verbose_name='Квалификация')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ссылки на социальные сети (instagram, facebook, etc.)', verbose_name='Социальные сети')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
                'db_table': 'instructors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['specialization'], name='instructors_special_3fd997_idx'), models.Index(fields=['is_active'], name='instructors_is_acti_822a26_idx')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.instructor', verbose_name='Инструктор'),
        ),
    ]
