# Generated by Django 4.2.8 on 2025-12-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_course_instructor_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография инструктора'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя инструктора'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
