# Generated by Django 4.2.8 on 2025-12-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_add_course_builder_models'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_user_avatar_user_bio_user_city_user_date_of_birth_and_more'),
        ('pets', '0006_pet_behavior_type_pet_behavioral_problems_and_more'),
    ]

    operations = [
        # Создание таблицы course_pages
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('page_type', models.CharField(
                    blank=True,
                    choices=[
                        ('text', 'Текстовая'),
                        ('video', 'Видео'),
                        ('interactive', 'Интерактивная'),
                        ('quiz', 'Тест'),
                        ('webinar', 'Вебинар'),
                        ('assignment', 'Задание'),
                    ],
                    max_length=20,
                    null=True,
                    verbose_name='Тип страницы'
                )),
                ('settings', models.JSONField(default=dict, help_text='JSON с настройками: required_completion, timer_enabled, allow_skipping и т.д.', verbose_name='Настройки страницы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='training.course', verbose_name='Курс')),
            ],
            options={
                'db_table': 'course_pages',
                'verbose_name': 'Страница курса',
                'verbose_name_plural': 'Страницы курсов',
                'ordering': ['course', 'order_number'],
                'unique_together': [['course', 'order_number']],
                'indexes': [
                    models.Index(fields=['course', 'order_number'], name='course_page_order_idx'),
                    models.Index(fields=['is_active'], name='course_page_active_idx'),
                ],
            },
        ),

        # Создание таблицы content_blocks
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_type', models.CharField(
                    choices=[
                        ('rich_text', 'Форматированный текст'),
                        ('image', 'Изображение'),
                        ('gallery', 'Галерея'),
                        ('file_download', 'Файл для скачивания'),
                        ('video_player', 'Видео-плеер'),
                        ('audio_player', 'Аудио-плеер'),
                        ('embed', 'Встраиваемый контент'),
                        ('quiz', 'Тест/Викторина'),
                        ('poll', 'Опрос'),
                        ('checklist', 'Чек-лист'),
                        ('timer', 'Таймер'),
                        ('pet_action', 'Действие с питомцем'),
                        ('progress_tracker', 'Трекер прогресса'),
                        ('comment_section', 'Комментарии'),
                        ('rating', 'Оценка'),
                    ],
                    max_length=30,
                    verbose_name='Тип блока'
                )),
                ('content', models.JSONField(default=dict, help_text='JSON с данными блока (зависит от типа)', verbose_name='Содержимое блока')),
                ('settings', models.JSONField(default=dict, help_text='JSON с настройками блока', verbose_name='Настройки блока')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='training.coursepage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'content_blocks',
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['page', 'order'],
                'unique_together': [['page', 'order']],
                'indexes': [
                    models.Index(fields=['page', 'order'], name='content_block_order_idx'),
                    models.Index(fields=['block_type'], name='content_block_type_idx'),
                    models.Index(fields=['is_active'], name='content_block_active_idx'),
                ],
            },
        ),

        # Создание таблицы block_templates
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('block_type', models.CharField(
                    choices=[
                        ('rich_text', 'Форматированный текст'),
                        ('image', 'Изображение'),
                        ('gallery', 'Галерея'),
                        ('file_download', 'Файл для скачивания'),
                        ('video_player', 'Видео-плеер'),
                        ('audio_player', 'Аудио-плеер'),
                        ('embed', 'Встраиваемый контент'),
                        ('quiz', 'Тест/Викторина'),
                        ('poll', 'Опрос'),
                        ('checklist', 'Чек-лист'),
                        ('timer', 'Таймер'),
                        ('pet_action', 'Действие с питомцем'),
                        ('progress_tracker', 'Трекер прогресса'),
                        ('comment_section', 'Комментарии'),
                        ('rating', 'Оценка'),
                    ],
                    max_length=30,
                    verbose_name='Тип блока'
                )),
                ('content', models.JSONField(default=dict, help_text='JSON с данными блока', verbose_name='Содержимое')),
                ('settings', models.JSONField(default=dict, help_text='JSON с настройками блока', verbose_name='Настройки')),
                ('category', models.CharField(
                    choices=[
                        ('text', 'Текстовые'),
                        ('media', 'Медиа'),
                        ('interactive', 'Интерактивные'),
                        ('pet_specific', 'Для питомцев'),
                        ('utility', 'Утилиты'),
                    ],
                    default='text',
                    max_length=50,
                    verbose_name='Категория'
                )),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный шаблон')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='block_templates',
                    to='users.user',
                    verbose_name='Создатель'
                )),
            ],
            options={
                'db_table': 'block_templates',
                'verbose_name': 'Шаблон блока',
                'verbose_name_plural': 'Шаблоны блоков',
                'ordering': ['-usage_count', 'name'],
                'indexes': [
                    models.Index(fields=['block_type'], name='block_tmpl_type_idx'),
                    models.Index(fields=['category'], name='block_tmpl_category_idx'),
                    models.Index(fields=['is_public'], name='block_tmpl_public_idx'),
                    models.Index(fields=['-usage_count'], name='block_tmpl_usage_idx'),
                ],
            },
        ),
    ]
