# Generated by Django 4.2.8 on 2025-12-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_create_course_builder_models'),
    ]

    operations = [
    ]
