# Generated by Django 4.2.8 on 2026-01-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_manual_course_builder_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Страница курса', 'verbose_name_plural': 'Страницы курсов'},
        ),
        migrations.AddField(
            model_name='coursepage',
            name='course_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID курса'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='course',
        ),
    ]
