# Generated by Django 4.2.8 on 2026-01-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_manual_course_builder_models'),
    ]

    operations = [
    ]
