# Generated by Django 4.2.8 on 2026-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_manual_course_builder_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Страница курса', 'verbose_name_plural': 'Страницы курсов'},
        ),
        migrations.RemoveIndex(
            model_name='coursepage',
            name='course_page_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursepage',
            name='course_page_active_idx',
        ),
        migrations.RenameIndex(
            model_name='blocktemplate',
            new_name='block_templ_block_t_f1151c_idx',
            old_name='block_tmpl_type_idx',
        ),
        migrations.RenameIndex(
            model_name='blocktemplate',
            new_name='block_templ_categor_0aa1cc_idx',
            old_name='block_tmpl_category_idx',
        ),
        migrations.RenameIndex(
            model_name='blocktemplate',
            new_name='block_templ_is_publ_972178_idx',
            old_name='block_tmpl_public_idx',
        ),
        migrations.RenameIndex(
            model_name='blocktemplate',
            new_name='block_templ_usage_c_bfce76_idx',
            old_name='block_tmpl_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='contentblock',
            new_name='content_blo_page_id_564c6d_idx',
            old_name='content_block_order_idx',
        ),
        migrations.RenameIndex(
            model_name='contentblock',
            new_name='content_blo_block_t_f61791_idx',
            old_name='content_block_type_idx',
        ),
        migrations.RenameIndex(
            model_name='contentblock',
            new_name='content_blo_is_acti_d1caa8_idx',
            old_name='content_block_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coursepage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='course_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID курса'),
        ),
        migrations.AlterField(
            model_name='blocktemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='course',
        ),
    ]
