# Generated by Django 4.2.8 on 2026-01-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_coursepage_changes'),
        ('training', '0013_skip_coursepage_changes'),
    ]

    operations = [
    ]
