# Generated by Django 5.1.5 on 2026-01-24 13:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_remove_rating_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'Страница курса', 'verbose_name_plural': 'Страницы курсов'},
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "DROP INDEX IF EXISTS course_page_order_idx; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "CREATE INDEX IF NOT EXISTS course_page_order_idx ON course_pages (order_number); "
                "END IF; "
                "END $$;"
            ),
            state_operations=[
                migrations.RemoveIndex(
                    model_name='coursepage',
                    name='course_page_order_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "DROP INDEX IF EXISTS course_page_active_idx; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "CREATE INDEX IF NOT EXISTS course_page_active_idx ON course_pages (is_active); "
                "END IF; "
                "END $$;"
            ),
            state_operations=[
                migrations.RemoveIndex(
                    model_name='coursepage',
                    name='course_page_active_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS block_tmpl_type_idx RENAME TO block_templ_block_t_f1151c_idx;",
            reverse_sql="ALTER INDEX IF EXISTS block_templ_block_t_f1151c_idx RENAME TO block_tmpl_type_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='blocktemplate',
                    new_name='block_templ_block_t_f1151c_idx',
                    old_name='block_tmpl_type_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS block_tmpl_category_idx RENAME TO block_templ_categor_0aa1cc_idx;",
            reverse_sql="ALTER INDEX IF EXISTS block_templ_categor_0aa1cc_idx RENAME TO block_tmpl_category_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='blocktemplate',
                    new_name='block_templ_categor_0aa1cc_idx',
                    old_name='block_tmpl_category_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS block_tmpl_public_idx RENAME TO block_templ_is_publ_972178_idx;",
            reverse_sql="ALTER INDEX IF EXISTS block_templ_is_publ_972178_idx RENAME TO block_tmpl_public_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='blocktemplate',
                    new_name='block_templ_is_publ_972178_idx',
                    old_name='block_tmpl_public_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS block_tmpl_usage_idx RENAME TO block_templ_usage_c_bfce76_idx;",
            reverse_sql="ALTER INDEX IF EXISTS block_templ_usage_c_bfce76_idx RENAME TO block_tmpl_usage_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='blocktemplate',
                    new_name='block_templ_usage_c_bfce76_idx',
                    old_name='block_tmpl_usage_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS content_block_order_idx RENAME TO content_blo_page_id_564c6d_idx;",
            reverse_sql="ALTER INDEX IF EXISTS content_blo_page_id_564c6d_idx RENAME TO content_block_order_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='contentblock',
                    new_name='content_blo_page_id_564c6d_idx',
                    old_name='content_block_order_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS content_block_type_idx RENAME TO content_blo_block_t_f61791_idx;",
            reverse_sql="ALTER INDEX IF EXISTS content_blo_block_t_f61791_idx RENAME TO content_block_type_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='contentblock',
                    new_name='content_blo_block_t_f61791_idx',
                    old_name='content_block_type_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS content_block_active_idx RENAME TO content_blo_is_acti_d1caa8_idx;",
            reverse_sql="ALTER INDEX IF EXISTS content_blo_is_acti_d1caa8_idx RENAME TO content_block_active_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='contentblock',
                    new_name='content_blo_is_acti_d1caa8_idx',
                    old_name='content_block_active_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "ALTER TABLE course_pages "
                "DROP CONSTRAINT IF EXISTS course_pages_course_id_order_number_key; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql="",
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='coursepage',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF EXISTS (SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'course_pages') THEN "
                "IF NOT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = 'public' AND table_name = 'course_pages' AND column_name = 'course_id') THEN "
                "ALTER TABLE course_pages ADD COLUMN course_id integer NULL; "
                "END IF; "
                "ALTER TABLE course_pages DROP CONSTRAINT IF EXISTS course_pages_course_id_fkey; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql="",
            state_operations=[
                migrations.AddField(
                    model_name='coursepage',
                    name='course_id',
                    field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID курса'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='blocktemplate',
                    name='content',
                    field=models.JSONField(default=dict, help_text='JSON с данными блока', validators=[core.validators.validate_content_block_content], verbose_name='Содержимое'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='blocktemplate',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='blocktemplate',
                    name='settings',
                    field=models.JSONField(default=dict, help_text='JSON с настройками блока', validators=[core.validators.validate_content_block_settings], verbose_name='Настройки'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachments',
            field=models.JSONField(default=list, help_text='Список URL вложений (фото, видео питомца и т.д.)', validators=[core.validators.validate_url_list], verbose_name='Вложения'),
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='contentblock',
                    name='content',
                    field=models.JSONField(default=dict, help_text='JSON с данными блока (зависит от типа)', validators=[core.validators.validate_content_block_content], verbose_name='Содержимое блока'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='contentblock',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='contentblock',
                    name='settings',
                    field=models.JSONField(default=dict, help_text='JSON с настройками блока', validators=[core.validators.validate_content_block_settings], verbose_name='Настройки блока'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='Массив URL дополнительных изображений курса', validators=[core.validators.validate_url_list], verbose_name='Дополнительные изображения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='addresses_behavioral_problems',
            field=models.JSONField(blank=True, default=list, help_text='Список поведенческих проблем, которые решает курс', validators=[core.validators.validate_string_list], verbose_name='Решаемые поведенческие проблемы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='addresses_special_needs',
            field=models.JSONField(blank=True, default=list, help_text='Список особых потребностей, которые учитывает курс', validators=[core.validators.validate_string_list], verbose_name='Учитываемые особые потребности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='compatible_health_issues',
            field=models.JSONField(blank=True, default=list, help_text='Список проблем здоровья, с которыми совместим курс', validators=[core.validators.validate_string_list], verbose_name='Совместимые проблемы здоровья'),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_activity_levels',
            field=models.JSONField(blank=True, default=list, help_text='Список уровней активности, для которых подходит курс (low, medium, high)', validators=[core.validators.validate_activity_levels], verbose_name='Рекомендуемые уровни активности'),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_behavior_types',
            field=models.JSONField(blank=True, default=list, help_text='Список типов поведения, для которых подходит курс (calm, active, aggressive, shy, playful)', validators=[core.validators.validate_behavior_types], verbose_name='Рекомендуемые типы поведения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_social_levels',
            field=models.JSONField(blank=True, default=list, help_text='Список уровней социализации, для которых подходит курс (home_only, street, social, mixed)', validators=[core.validators.validate_social_levels], verbose_name='Рекомендуемые уровни социализации'),
        ),
        migrations.AlterField(
            model_name='course',
            name='suitable_activities',
            field=models.JSONField(blank=True, default=list, help_text='Виды активностей питомца, для которых подходит курс', validators=[core.validators.validate_string_list], verbose_name='Подходящие активности'),
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='coursepage',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='additional_materials',
            field=models.JSONField(default=list, help_text='Список дополнительных материалов (PDF, ссылки и т.д.)', validators=[core.validators.validate_url_list], verbose_name='Дополнительные материалы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(default=dict, help_text='JSON структура с контентом урока (зависит от типа)', validators=[core.validators.validate_lesson_content], verbose_name='Контент урока'),
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.RemoveField(
                    model_name='coursepage',
                    name='course',
                ),
            ],
        ),
    ]
