# Generated by Django 4.2.8 on 2026-02-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_add_completed_pages_ids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together=set(),
        ),
    ]
