# Generated by Django 4.2.8 on 2026-02-17 19:51

from django.db import migrations, models


def set_existing_active_to_published(apps, schema_editor):
    Course = apps.get_model('training', 'Course')
    Course.objects.filter(is_active=True).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_remove_unique_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.RunPython(set_existing_active_to_published, migrations.RunPython.noop),
    ]
