# Generated by Django 4.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_add_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='training.coursepage',
                verbose_name='Страница'
            ),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['page', '-created_at'], name='comments_page_i_idx'),
        ),
    ]
