# Generated by Django 5.1.5 on 2026-02-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_comment_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'ordering': ['order_number', 'id'], 'verbose_name': 'Страница курса', 'verbose_name_plural': 'Страницы курсов'},
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_page_id_55a7e3_idx',
            old_name='comments_page_i_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
    ]
