# Generated by Django 4.2.8 on 2025-12-24 21:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_add_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('veterinary', 'Ветеринарный визит'), ('vaccination', 'Прививка'), ('grooming', 'Уход за шерстью'), ('birthday', 'День рождения'), ('medication', 'Приём лекарств'), ('training', 'Тренировка'), ('walking', 'Прогулка'), ('feeding', 'Кормление'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющееся событие')),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, verbose_name='Правило повторения')),
                ('notify_before', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Напомнить за (минут)')),
                ('email_notification', models.BooleanField(default=True, verbose_name='Уведомление по email')),
                ('push_notification', models.BooleanField(default=True, verbose_name='Push-уведомление')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push-уведомление'), ('sms', 'SMS')], max_length=10, verbose_name='Тип напоминания')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar.calendarevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
