# Generated by Django 4.2.8 on 2025-12-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_product_review',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_course_review',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_product_4bb590_idx',
            old_name='reviews_product_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_course__f254ac_idx',
            old_name='reviews_course_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_user_id_e08f48_idx',
            old_name='reviews_user_type_idx',
        ),
    ]
