// Экспорт компонентов системы обучения
export { default as ProgressTracker } from './ProgressTracker'
export { default as CommentsSection } from './CommentsSection'
export { default as RatingWidget } from './RatingWidget'
export { default as LessonPlayer } from './LessonPlayer'
export { default as CourseRecommendations } from './CourseRecommendations'
export { default as CoursePersonalizationWidget } from './CoursePersonalizationWidget'
export { default as ContentProtection } from './ContentProtection'
export { default as ModuleSidebar } from './ModuleSidebar'
export { default as StepNavigation } from './StepNavigation'