# Generated by Django 4.2.8 on 2025-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='Список продуктов или ингредиентов, на которые у питомца аллергия', verbose_name='Аллергии'),
        ),
        migrations.AddField(
            model_name='pet',
            name='favorite_foods',
            field=models.JSONField(blank=True, default=list, help_text='Список названий продуктов или кормов, которые любит питомец', verbose_name='Любимые продукты/корма'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Самец'), ('female', 'Самка'), ('unknown', 'Не указан')], default='unknown', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Кастрирован/Стерилизован'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/', verbose_name='Фото'),
        ),
    ]
