# Generated by Django 4.2.8 on 2025-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_breed_alter_pet_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', help_text='Уровень физической активности питомца', max_length=10, verbose_name='Уровень активности'),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_issues',
            field=models.JSONField(blank=True, default=list, help_text='Список проблем здоровья питомца (лишний вес, чувствительное пищеварение и т.д.)', verbose_name='Проблемы здоровья'),
        ),
    ]
