# Generated by Django 4.2.8 on 2025-12-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_add_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='behavior_type',
            field=models.CharField(blank=True, choices=[('calm', 'Спокойный'), ('active', 'Активный'), ('aggressive', 'Агрессивный'), ('shy', 'Трусливый'), ('playful', 'Игривый')], help_text='Основной тип поведения питомца для персонализации курсов', max_length=20, null=True, verbose_name='Тип поведения'),
        ),
        migrations.AddField(
            model_name='pet',
            name='behavioral_problems',
            field=models.JSONField(blank=True, default=list, help_text='Поведенческие проблемы питомца для персонализированных курсов коррекции', verbose_name='Поведенческие проблемы'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_extended_profile',
            field=models.BooleanField(default=False, help_text='Показывает, заполнены ли расширенные поля профиля PetID', verbose_name='Расширенный профиль заполнен'),
        ),
        migrations.AddField(
            model_name='pet',
            name='preferred_activities',
            field=models.JSONField(blank=True, default=list, help_text='Виды активностей, которые предпочитает питомец', verbose_name='Предпочитаемые активности'),
        ),
        migrations.AddField(
            model_name='pet',
            name='social_level',
            field=models.CharField(blank=True, choices=[('home_only', 'Только домашний'), ('street', 'Уличный'), ('social', 'Социальный'), ('mixed', 'Смешанный')], help_text='Уровень социализации питомца (домашний/уличный/социальный)', max_length=20, null=True, verbose_name='Уровень социализации'),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_needs',
            field=models.JSONField(blank=True, default=list, help_text='Особые потребности питомца (инвалидность, хронические заболевания и т.д.)', verbose_name='Особые потребности'),
        ),
        migrations.AddField(
            model_name='pet',
            name='training_experience',
            field=models.CharField(blank=True, choices=[('none', 'Без опыта'), ('basic', 'Базовый'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('professional', 'Профессиональный')], help_text='Уровень опыта дрессировки питомца', max_length=20, null=True, verbose_name='Опыт дрессировки'),
        ),
    ]
