# Generated by Django 4.2.8 on 2026-01-08 17:59

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_add_petid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='Список продуктов или ингредиентов, на которые у питомца аллергия', validators=[core.validators.validate_string_list], verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='behavioral_problems',
            field=models.JSONField(blank=True, default=list, help_text='Поведенческие проблемы питомца для персонализированных курсов коррекции', validators=[core.validators.validate_string_list], verbose_name='Поведенческие проблемы'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='character_traits',
            field=models.JSONField(blank=True, default=list, validators=[core.validators.validate_string_list], verbose_name='Черты характера'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='excluded_ingredients',
            field=models.JSONField(blank=True, default=list, validators=[core.validators.validate_string_list], verbose_name='Исключаемые ингредиенты'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='favorite_foods',
            field=models.JSONField(blank=True, default=list, help_text='Список названий продуктов или кормов, которые любит питомец', validators=[core.validators.validate_string_list], verbose_name='Любимые продукты/корма'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_issues',
            field=models.JSONField(blank=True, default=list, help_text='Список проблем здоровья питомца (лишний вес, чувствительное пищеварение и т.д.)', validators=[core.validators.validate_string_list], verbose_name='Проблемы здоровья'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='preferred_activities',
            field=models.JSONField(blank=True, default=list, help_text='Виды активностей, которые предпочитает питомец', validators=[core.validators.validate_string_list], verbose_name='Предпочитаемые активности'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.JSONField(blank=True, default=list, help_text='Особые потребности питомца (инвалидность, хронические заболевания и т.д.)', validators=[core.validators.validate_string_list], verbose_name='Особые потребности'),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название породы')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL-slug')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], max_length=10, verbose_name='Вид животного')),
                ('description', models.TextField(help_text='Полное описание породы', verbose_name='Описание породы')),
                ('health_risk_level', models.CharField(choices=[('low', 'Низкий риск'), ('medium', 'Средний риск'), ('high', 'Высокий риск')], default='medium', max_length=20, verbose_name='Уровень риска здоровья')),
                ('genetic_risks', models.JSONField(default=list, help_text='Список генетических заболеваний породы', verbose_name='Генетические риски')),
                ('lifespan_min', models.IntegerField(default=10, verbose_name='Минимальная продолжительность жизни (лет)')),
                ('lifespan_max', models.IntegerField(default=15, verbose_name='Максимальная продолжительность жизни (лет)')),
                ('dental_health_notes', models.TextField(blank=True, verbose_name='Особенности стоматологического здоровья')),
                ('weight_min', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Минимальный вес (кг)')),
                ('weight_max', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Максимальный вес (кг)')),
                ('size_category', models.CharField(choices=[('toy', 'Миниатюрный (до 5 кг)'), ('small', 'Маленький (5-10 кг)'), ('medium', 'Средний (10-25 кг)'), ('large', 'Крупный (25-45 кг)'), ('giant', 'Гигантский (45+ кг)')], max_length=20, verbose_name='Категория размера')),
                ('diet_recommendations', models.TextField(blank=True, verbose_name='Рекомендации по питанию')),
                ('digestion_sensitivity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=20, verbose_name='Чувствительность пищеварения')),
                ('metabolism_notes', models.TextField(blank=True, verbose_name='Особенности метаболизма')),
                ('energy_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('very_high', 'Очень высокий')], default='medium', max_length=20, verbose_name='Уровень энергии')),
                ('exercise_needs', models.TextField(blank=True, verbose_name='Рекомендации по прогулкам/играм')),
                ('favorite_activities', models.JSONField(default=list, verbose_name='Любимые активности')),
                ('activity_notes', models.TextField(blank=True, verbose_name='Особенности активности')),
                ('grooming_level', models.CharField(choices=[('minimal', 'Минимальный'), ('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Уровень ухода за шерстью')),
                ('bathing_frequency', models.CharField(blank=True, max_length=100, verbose_name='Частота купания')),
                ('grooming_notes', models.TextField(blank=True, verbose_name='Особенности ухода')),
                ('temperament', models.JSONField(default=list, verbose_name='Черты темперамента')),
                ('trainability', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('very_high', 'Очень высокая')], default='medium', max_length=20, verbose_name='Обучаемость')),
                ('children_compatibility', models.CharField(choices=[('excellent', 'Отличная'), ('good', 'Хорошая'), ('moderate', 'Средняя'), ('poor', 'Низкая')], default='good', max_length=20, verbose_name='Совместимость с детьми')),
                ('socialization_notes', models.TextField(blank=True, verbose_name='Особенности социализации')),
                ('popularity_rank', models.IntegerField(default=0, verbose_name='Рейтинг популярности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'db_table': 'breeds',
                'ordering': ['species', 'name'],
                'indexes': [models.Index(fields=['species', 'is_active'], name='breeds_species_2b54e3_idx'), models.Index(fields=['slug'], name='breeds_slug_daff52_idx'), models.Index(fields=['popularity_rank'], name='breeds_popular_ac897d_idx')],
            },
        ),
    ]
