# Generated by Django 4.2.8 on 2026-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_add_petid_fields'),
    ]

    operations = [
        # Расширенное питание
        migrations.AddField(
            model_name='pet',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('dry', 'Сухой корм'), ('wet', 'Влажный корм'), ('mixed', 'Смешанное питание'), ('raw', 'Натуральное питание'), ('home', 'Домашняя еда')], max_length=20, null=True, verbose_name='Тип питания'),
        ),
        migrations.AddField(
            model_name='pet',
            name='feeding_frequency',
            field=models.CharField(blank=True, choices=[('1', '1 раз в день'), ('2', '2 раза в день'), ('3', '3 раза в день'), ('free', 'Свободный доступ')], max_length=10, null=True, verbose_name='Частота кормления'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sensitive_digestion',
            field=models.BooleanField(default=False, verbose_name='Чувствительное пищеварение'),
        ),
        migrations.AddField(
            model_name='pet',
            name='excluded_ingredients',
            field=models.JSONField(blank=True, default=list, verbose_name='Исключаемые ингредиенты'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vitamins_supplements',
            field=models.TextField(blank=True, verbose_name='Добавки и витамины'),
        ),
        # Расширенное поведение
        migrations.AddField(
            model_name='pet',
            name='character_traits',
            field=models.JSONField(blank=True, default=list, verbose_name='Черты характера'),
        ),
        migrations.AddField(
            model_name='pet',
            name='training_goals',
            field=models.TextField(blank=True, verbose_name='Цели дрессировки'),
        ),
        # Расширенное здоровье
        migrations.AddField(
            model_name='pet',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinations',
            field=models.TextField(blank=True, verbose_name='Вакцинации'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medications',
            field=models.TextField(blank=True, verbose_name='Принимаемые препараты'),
        ),
        migrations.AddField(
            model_name='pet',
            name='dental_health',
            field=models.CharField(blank=True, choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное'), ('needs_attention', 'Требует лечения')], max_length=20, null=True, verbose_name='Состояние зубов'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_visits',
            field=models.TextField(blank=True, verbose_name='Посещения ветеринара'),
        ),
        # Образ жизни
        migrations.AddField(
            model_name='pet',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Частный дом'), ('cottage', 'Дача/Коттедж'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='pet',
            name='has_yard',
            field=models.BooleanField(default=False, verbose_name='Есть двор'),
        ),
        migrations.AddField(
            model_name='pet',
            name='other_pets',
            field=models.TextField(blank=True, verbose_name='Другие питомцы дома'),
        ),
        migrations.AddField(
            model_name='pet',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='В доме есть дети'),
        ),
        migrations.AddField(
            model_name='pet',
            name='walk_frequency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Частота прогулок'),
        ),
        migrations.AddField(
            model_name='pet',
            name='walk_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность прогулки'),
        ),
    ]
