# Generated by Django 4.2.8 on 2026-01-09 10:15

from django.db import migrations


def convert_text_to_json(apps, schema_editor):
    """Конвертация текстовых полей в JSON массивы через Django ORM."""
    Pet = apps.get_model('pets', 'Pet')

    # Конвертируем текстовые поля в JSON массивы
    fields_to_convert = [
        'vitamins_supplements',
        'training_goals',
        'chronic_conditions',
        'vaccinations',
        'medications',
        'other_pets'
    ]

    for pet in Pet.objects.all():
        for field_name in fields_to_convert:
            current_value = getattr(pet, field_name)

            # Если поле пустое или уже является списком, пропускаем
            if not current_value or isinstance(current_value, list):
                continue

            # Конвертация строки в массив
            if isinstance(current_value, str):
                # Разделяем по запятым и очищаем пробелы
                items = [item.strip() for item in current_value.split(',') if item.strip()]
                # Фильтруем пустые элементы
                items = [item for item in items if item]
                setattr(pet, field_name, items)
            else:
                # Если не строка, устанавливаем пустой массив
                setattr(pet, field_name, [])

        pet.save(update_fields=fields_to_convert)


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_add_breed_model'),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, migrations.RunPython.noop),
    ]
