# Generated by Django 4.2.8 on 2026-01-09 10:07

import core.validators
from django.db import migrations, models


def convert_text_to_json(apps, schema_editor):
    """Конвертация текстовых полей в JSON массивы через Django ORM."""
    Pet = apps.get_model('pets', 'Pet')

    # Конвертируем текстовые поля в JSON массивы
    fields_to_convert = [
        'vitamins_supplements',
        'training_goals',
        'chronic_conditions',
        'vaccinations',
        'medications',
        'other_pets'
    ]

    for pet in Pet.objects.all():
        for field_name in fields_to_convert:
            current_value = getattr(pet, field_name)

            # Если поле пустое или уже является списком, пропускаем
            if not current_value or isinstance(current_value, list):
                continue

            # Конвертация строки в массив
            if isinstance(current_value, str):
                # Разделяем по запятым и очищаем пробелы
                items = [item.strip() for item in current_value.split(',') if item.strip()]
                # Фильтруем пустые элементы
                items = [item for item in items if item]
                setattr(pet, field_name, items)
            else:
                # Если не строка, устанавливаем пустой массив
                setattr(pet, field_name, [])

        pet.save(update_fields=fields_to_convert)


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_add_breed_model'),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='pet',
            name='body_condition_score',
            field=models.CharField(blank=True, choices=[('1', '1 - Истощение'), ('2', '2 - Очень худой'), ('3', '3 - Худой'), ('4', '4 - Недостаток веса'), ('5', '5 - Идеальный вес'), ('6', '6 - Избыток веса'), ('7', '7 - Полнота'), ('8', '8 - Ожирение'), ('9', '9 - Тяжёлое ожирение')], help_text='Шкала от 1 до 9', max_length=2, null=True, verbose_name='Оценка упитанности (BCS)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Частота сердечных сокращений', null=True, verbose_name='ЧСС (уд/мин)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_vet_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего осмотра'),
        ),
        migrations.AddField(
            model_name='pet',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Частота дыхательных движений', null=True, verbose_name='ЧДД (дых/мин)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура (°C)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_notes',
            field=models.TextField(blank=True, help_text='Дополнительные наблюдения и рекомендации врача', verbose_name='Заметки ветеринара'),
        ),

        # Изменяем choices для walk_duration и walk_frequency
        migrations.AlterField(
            model_name='pet',
            name='walk_duration',
            field=models.CharField(blank=True, choices=[('under_15', 'Менее 15 минут'), ('15_30', '15-30 минут'), ('30_60', '30-60 минут'), ('60_90', '1-1.5 часа'), ('90_120', '1.5-2 часа'), ('over_120', 'Более 2 часов')], max_length=20, null=True, verbose_name='Длительность прогулки'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='walk_frequency',
            field=models.CharField(blank=True, choices=[('none', 'Не гуляет'), ('1_day', '1 раз в день'), ('2_day', '2 раза в день'), ('3_day', '3 раза в день'), ('4_plus', '4+ раз в день'), ('free_access', 'Свободный выгул')], max_length=20, null=True, verbose_name='Частота прогулок'),
        ),

        # Теперь конвертируем данные
        migrations.RunPython(convert_text_to_json, migrations.RunPython.noop),

        # Потом меняем типы полей
        migrations.AlterField(
            model_name='pet',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Список хронических заболеваний из справочника', validators=[core.validators.validate_string_list], verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medications',
            field=models.JSONField(blank=True, default=list, help_text='Список препаратов с дозировками и частотой приёма', verbose_name='Принимаемые препараты'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='other_pets',
            field=models.JSONField(blank=True, default=list, help_text='Список других питомцев с типом и кличкой', verbose_name='Другие питомцы дома'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='training_goals',
            field=models.JSONField(blank=True, default=list, help_text='Список целей дрессировки из предопределённого списка', validators=[core.validators.validate_string_list], verbose_name='Цели дрессировки'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccinations',
            field=models.JSONField(blank=True, default=list, help_text='Список вакцинаций с датами и следующими датами', verbose_name='Вакцинации'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vitamins_supplements',
            field=models.JSONField(blank=True, default=list, help_text='Список витаминов и добавок из справочника', validators=[core.validators.validate_string_list], verbose_name='Добавки и витамины'),
        ),
    ]
