# Generated by Django 5.1.5 on 2026-01-12 20:26

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_recreate_breed_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('veterinary', 'Ветеринарный визит'), ('vaccination', 'Прививка'), ('grooming', 'Уход за шерстью'), ('birthday', 'День рождения'), ('medication', 'Приём лекарств'), ('training', 'Тренировка'), ('walking', 'Прогулка'), ('feeding', 'Кормление'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющееся событие')),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, verbose_name='Правило повторения')),
                ('notify_before', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Напомнить за (минут)')),
                ('email_notification', models.BooleanField(default=True, verbose_name='Уведомление по email')),
                ('push_notification', models.BooleanField(default=True, verbose_name='Push-уведомление')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push-уведомление'), ('sms', 'SMS')], max_length=10, verbose_name='Тип напоминания')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='breedcare',
            options={'ordering': ['breed', '-importance', 'care_category'], 'verbose_name': 'Процедура ухода за породой', 'verbose_name_plural': 'Процедуры ухода за породами'},
        ),
        migrations.RenameIndex(
            model_name='breed',
            new_name='breeds_species_7e5ace_idx',
            old_name='breeds_sp_size_idx',
        ),
        migrations.RenameIndex(
            model_name='breed',
            new_name='breeds_energy__1831df_idx',
            old_name='breeds_energy_idx',
        ),
        migrations.RenameIndex(
            model_name='breed',
            new_name='breeds_health__4d6651_idx',
            old_name='breeds_health_idx',
        ),
        migrations.RenameIndex(
            model_name='breedcare',
            new_name='breed_care_breed_i_b14ab8_idx',
            old_name='breedcare_br_imp_idx',
        ),
        migrations.RenameIndex(
            model_name='breedcare',
            new_name='breed_care_care_ca_80342e_idx',
            old_name='breedcare_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='breedhealth',
            new_name='breed_healt_breed_i_1493c7_idx',
            old_name='breedhlth_br_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='breedhealth',
            new_name='breed_healt_affecte_8e7305_idx',
            old_name='breedhlth_sys_idx',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vet_visits',
        ),
        migrations.AddField(
            model_name='pet',
            name='body_condition_score',
            field=models.CharField(blank=True, choices=[('1', '1 - Истощение'), ('2', '2 - Очень худой'), ('3', '3 - Худой'), ('4', '4 - Недостаток веса'), ('5', '5 - Идеальный вес'), ('6', '6 - Избыток веса'), ('7', '7 - Полнота'), ('8', '8 - Ожирение'), ('9', '9 - Тяжёлое ожирение')], help_text='Шкала от 1 до 9', max_length=2, null=True, verbose_name='Оценка упитанности (BCS)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Частота сердечных сокращений', null=True, verbose_name='ЧСС (уд/мин)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_vet_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего осмотра'),
        ),
        migrations.AddField(
            model_name='pet',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Частота дыхательных движений', null=True, verbose_name='ЧДД (дых/мин)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура (°C)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_notes',
            field=models.TextField(blank=True, help_text='Дополнительные наблюдения и рекомендации врача', verbose_name='Заметки ветеринара'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='height_max',
            field=models.IntegerField(blank=True, help_text='Только для собак', null=True, verbose_name='Максимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='height_min',
            field=models.IntegerField(blank=True, help_text='Только для собак', null=True, verbose_name='Минимальный рост (см)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size_category',
            field=models.CharField(choices=[('toy', 'Toy (до 5 кг)'), ('small', 'Small (5-10 кг)'), ('medium', 'Medium (10-25 кг)'), ('large', 'Large (25-40 кг)'), ('giant', 'Giant (40+ кг)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='breed',
            name='weight_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Максимальный вес (кг)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='weight_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Минимальный вес (кг)'),
        ),
        migrations.AlterField(
            model_name='breednutrition',
            name='common_allergens',
            field=models.JSONField(blank=True, default=list, help_text='Список аллергенов, характерных для породы', verbose_name='Породоспецифичные аллергены'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Список хронических заболеваний из справочника', validators=[core.validators.validate_string_list], verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medications',
            field=models.JSONField(blank=True, default=list, help_text='Список препаратов с дозировками и частотой приёма', verbose_name='Принимаемые препараты'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='other_pets',
            field=models.JSONField(blank=True, default=list, help_text='Список других питомцев с типом и кличкой', verbose_name='Другие питомцы дома'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='training_goals',
            field=models.JSONField(blank=True, default=list, help_text='Список целей дрессировки из предопределённого списка', validators=[core.validators.validate_string_list], verbose_name='Цели дрессировки'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccinations',
            field=models.JSONField(blank=True, default=list, help_text='Список вакцинаций с датами и следующими датами', verbose_name='Вакцинации'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vitamins_supplements',
            field=models.JSONField(blank=True, default=list, help_text='Список витаминов и добавок из справочника', validators=[core.validators.validate_string_list], verbose_name='Добавки и витамины'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='walk_duration',
            field=models.CharField(blank=True, choices=[('under_15', 'Менее 15 минут'), ('15_30', '15-30 минут'), ('30_60', '30-60 минут'), ('60_90', '1-1.5 часа'), ('90_120', '1.5-2 часа'), ('over_120', 'Более 2 часов')], max_length=20, null=True, verbose_name='Длительность прогулки'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='walk_frequency',
            field=models.CharField(blank=True, choices=[('none', 'Не гуляет'), ('1_day', '1 раз в день'), ('2_day', '2 раза в день'), ('3_day', '3 раза в день'), ('4_plus', '4+ раз в день'), ('free_access', 'Свободный выгул')], max_length=20, null=True, verbose_name='Частота прогулок'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.calendarevent', verbose_name='Событие'),
        ),
    ]
