# Generated by Django 4.2.8 on 2026-01-19 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_calendarevent_eventreminder_alter_breedcare_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('code', models.CharField(help_text='Уникальный код, например: dog_beef_protein, chicken_protein', max_length=50, primary_key=True, serialize=False, verbose_name='Код аллергии')),
                ('animal_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('both', 'Оба')], max_length=10, verbose_name='Вид животного')),
                ('allergen_type', models.CharField(choices=[('Environmental', 'Окружающая среда'), ('Food', 'Пищевая'), ('Flea', 'Блохи'), ('Contact', 'Контактная'), ('Drug', 'Лекарственная'), ('Seasonal', 'Сезонная')], db_index=True, max_length=20, verbose_name='Тип аллергена')),
                ('specific_allergen', models.CharField(max_length=200, verbose_name='Аллерген')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое название')),
                ('prevalence_rate', models.CharField(choices=[('Rare', 'Редкая'), ('Uncommon', 'Нечастая'), ('Common', 'Частая'), ('Very Common', 'Очень частая')], default='Common', max_length=20, verbose_name='Распространённость')),
                ('typical_symptoms', models.TextField(blank=True, verbose_name='Типичные симптомы')),
                ('diagnostic_approach', models.TextField(blank=True, verbose_name='Диагностика')),
                ('management_strategies', models.TextField(blank=True, verbose_name='Управление')),
                ('seasonal_pattern', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сезонность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
                'db_table': 'allergies',
                'ordering': ['allergen_type', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('code', models.CharField(help_text='Уникальный код, например: obesity_1, diabetes, ckd_1_2', max_length=50, primary_key=True, serialize=False, verbose_name='Код заболевания')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (англ)')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('both', 'Оба')], default='both', max_length=10, verbose_name='Вид животного')),
                ('category', models.CharField(choices=[('metabolic', 'Метаболические'), ('endocrine', 'Эндокринные'), ('renal', 'Почечные'), ('hepatic', 'Печёночные'), ('gastrointestinal', 'ЖКТ'), ('cardiovascular', 'Сердечно-сосудистые'), ('musculoskeletal', 'Опорно-двигательные'), ('immune', 'Иммунные'), ('oncology', 'Онкология'), ('urinary', 'Мочевыводящие'), ('dental', 'Стоматологические'), ('recovery', 'Восстановление'), ('other', 'Другое')], db_index=True, max_length=30, verbose_name='Категория')),
                ('coefficient_min', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='Мин. коэффициент')),
                ('coefficient_max', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='Макс. коэффициент')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('CRITICAL', 'Критический')], default='MEDIUM', max_length=10, verbose_name='Приоритет')),
                ('direction', models.CharField(choices=[('INCREASE', 'Увеличение калорий'), ('DECREASE', 'Уменьшение калорий'), ('NEUTRAL', 'Без изменений')], default='NEUTRAL', max_length=10, verbose_name='Направление изменения')),
                ('symptoms', models.JSONField(blank=True, default=list, verbose_name='Симптомы')),
                ('dietary_recommendations', models.JSONField(blank=True, default=dict, verbose_name='Рекомендации по питанию')),
                ('contraindicated_ingredients', models.JSONField(blank=True, default=list, verbose_name='Противопоказанные ингредиенты')),
                ('bcs_range_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BCS мин')),
                ('bcs_range_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BCS макс')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Клинические заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
                'db_table': 'health_conditions',
                'ordering': ['category', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='NutritionCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код: dog_toy, cat_kitten_weaning, и т.д.', max_length=50, verbose_name='Код')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], max_length=10, verbose_name='Вид')),
                ('coefficient_type', models.CharField(choices=[('size_category', 'Размер'), ('age', 'Возраст'), ('activity_level', 'Активность'), ('neutering', 'Кастрация'), ('coat_type', 'Тип шерсти'), ('climate', 'Климат'), ('housing', 'Тип жилья'), ('reproductive', 'Репродуктивное состояние')], db_index=True, max_length=20, verbose_name='Тип коэффициента')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='Коэффициент')),
                ('coefficient_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Мин. коэффициент')),
                ('coefficient_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Макс. коэффициент')),
                ('weight_min_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Мин. вес (кг)')),
                ('weight_max_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Макс. вес (кг)')),
                ('age_from_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от (мес)')),
                ('age_to_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до (мес)')),
                ('daily_activity_hours_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Макс. часов активности в день')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('examples', models.TextField(blank=True, verbose_name='Примеры пород')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коэффициент питания',
                'verbose_name_plural': 'Коэффициенты питания',
                'db_table': 'nutrition_coefficients',
                'ordering': ['coefficient_type', 'species', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PetAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_breed_risk', models.BooleanField(default=False, help_text='Автоматически добавлено из базы знаний пород', verbose_name='Породный риск')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Дата выявления')),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Лёгкая'), ('moderate', 'Умеренная'), ('severe', 'Тяжёлая')], max_length=20, verbose_name='Тяжесть')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аллергия питомца',
                'verbose_name_plural': 'Аллергии питомцев',
                'db_table': 'pet_allergies',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetFoodExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_code', models.CharField(help_text='Код из справочника: chicken_protein, wheat_protein и т.д.', max_length=50, verbose_name='Код ингредиента')),
                ('ingredient_name', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('reason', models.CharField(choices=[('allergy', 'Аллергия'), ('intolerance', 'Непереносимость'), ('preference', 'Предпочтение владельца'), ('medical', 'Медицинские показания'), ('other', 'Другое')], default='allergy', max_length=20, verbose_name='Причина исключения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Исключение продукта',
                'verbose_name_plural': 'Исключения продуктов',
                'db_table': 'pet_food_exclusions',
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='PetHealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_breed_risk', models.BooleanField(default=False, help_text='Автоматически добавлено из базы знаний пород', verbose_name='Породный риск')),
                ('breed_risk_level', models.CharField(blank=True, max_length=20, verbose_name='Уровень породного риска')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Дата диагноза')),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Лёгкая'), ('moderate', 'Умеренная'), ('severe', 'Тяжёлая')], max_length=20, verbose_name='Тяжесть')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заболевание питомца',
                'verbose_name_plural': 'Заболевания питомцев',
                'db_table': 'pet_health_conditions',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='breednutrition',
            options={'verbose_name': 'Питание породы', 'verbose_name_plural': 'Рекомендации по питанию'},
        ),
        migrations.RemoveIndex(
            model_name='breed',
            name='breeds_species_7e5ace_idx',
        ),
        migrations.RemoveIndex(
            model_name='breed',
            name='breeds_energy__1831df_idx',
        ),
        migrations.RemoveIndex(
            model_name='breed',
            name='breeds_health__4d6651_idx',
        ),
        migrations.RemoveIndex(
            model_name='breedcare',
            name='breed_care_breed_i_b14ab8_idx',
        ),
        migrations.RemoveIndex(
            model_name='breedcare',
            name='breed_care_care_ca_80342e_idx',
        ),
        migrations.RemoveIndex(
            model_name='breedhealth',
            name='breed_healt_breed_i_1493c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='breedhealth',
            name='breed_healt_affecte_8e7305_idx',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='apartment_friendly',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='brachycephalic',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='friendliness_to_children',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='friendliness_to_pets',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='friendliness_to_strangers',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='good_for_novice',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='grooming_frequency',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='health_risk_level',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='height_max',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='height_min',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='hypoallergenic',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='independence',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='lifespan_max',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='lifespan_min',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='shedding_level',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='weight_min',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='character_traits',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dental_health',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='excluded_ingredients',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='favorite_foods',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='health_issues',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='other_pets',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_city',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='preferred_activities',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='special_needs',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='training_experience',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='training_goals',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccinations',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vitamins_supplements',
        ),
        migrations.AddField(
            model_name='breed',
            name='allergy_risks',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"allergen_code": "chicken_protein", "risk_level": "common"}, ...]', verbose_name='Риски аллергий'),
        ),
        migrations.AddField(
            model_name='breed',
            name='average_lifespan',
            field=models.PositiveIntegerField(default=12, verbose_name='Средняя продолжительность жизни (лет)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='base_activity_level',
            field=models.CharField(choices=[('very_low', 'Очень низкая'), ('low', 'Низкая'), ('moderate', 'Умеренная'), ('high', 'Высокая'), ('very_high', 'Очень высокая')], default='moderate', help_text='Для автозаполнения PetID', max_length=20, verbose_name='Базовый уровень активности'),
        ),
        migrations.AddField(
            model_name='breed',
            name='country_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='breed',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID из JSON файла (7001 для собак FCI, 1001 для кошек WCF)', max_length=20, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fci_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FCI группа'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fci_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='FCI номер'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fci_section',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FCI секция'),
        ),
        migrations.AddField(
            model_name='breed',
            name='fci_subsection',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FCI подсекция'),
        ),
        migrations.AddField(
            model_name='breed',
            name='grooming_needs',
            field=models.CharField(choices=[('minimal', 'Минимальный'), ('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий'), ('very_high', 'Очень высокий')], default='moderate', max_length=20, verbose_name='Потребность в уходе'),
        ),
        migrations.AddField(
            model_name='breed',
            name='health_risks',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"condition_code": "hip_dysplasia", "risk_level": "high"}, ...]', verbose_name='Риски здоровья'),
        ),
        migrations.AddField(
            model_name='breed',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='breed',
            name='short_description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (англ)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='wcf_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='WCF категория'),
        ),
        migrations.AddField(
            model_name='breed',
            name='wcf_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='WCF код'),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_female_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Макс. вес самки (кг)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_female_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Мин. вес самки (кг)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_male_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Макс. вес самца (кг)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_male_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Мин. вес самца (кг)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='chronic_conditions_notes',
            field=models.TextField(blank=True, help_text='Свободный текст для дополнительных заметок врача/владельца', verbose_name='Дополнительные заметки по здоровью'),
        ),
        migrations.AddField(
            model_name='pet',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('hairless', 'Бесшёрстный'), ('short', 'Короткая'), ('medium', 'Средняя'), ('long', 'Длинная'), ('double', 'Двойная (с подшёрстком)'), ('wire', 'Жёсткая'), ('curly', 'Курчавая')], help_text='Автозаполняется из породы или указывается вручную для дворняг', max_length=15, null=True, verbose_name='Тип шерсти'),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_food',
            field=models.JSONField(blank=True, default=dict, help_text='{"source": "catalog"|"other", "food_id": "uuid", "brand_name": "", "product_name": "", "daily_amount_grams": 250}', verbose_name='Текущий корм'),
        ),
        migrations.AddField(
            model_name='pet',
            name='has_other_pets',
            field=models.BooleanField(default=False, verbose_name='Есть другие питомцы'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ideal_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается из породы или указывается вручную', max_digits=5, null=True, verbose_name='Идеальный вес (кг)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='lactation_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Неделя лактации, если reproductive_state=lactating', null=True, verbose_name='Неделя лактации'),
        ),
        migrations.AddField(
            model_name='pet',
            name='litter_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Для расчёта калорий при лактации', null=True, verbose_name='Количество детёнышей'),
        ),
        migrations.AddField(
            model_name='pet',
            name='living_climate',
            field=models.CharField(choices=[('hot', 'Жаркий'), ('warm', 'Тёплый'), ('cool', 'Прохладный'), ('cold', 'Холодный'), ('very_cold', 'Очень холодный')], default='warm', max_length=15, verbose_name='Климат проживания'),
        ),
        migrations.AddField(
            model_name='pet',
            name='neutering_date',
            field=models.DateField(blank=True, help_text='Дата операции (если is_neutered=True)', null=True, verbose_name='Дата кастрации/стерилизации'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pregnancy_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Неделя беременности (1-9), если reproductive_state=pregnant', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Неделя беременности'),
        ),
        migrations.AddField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('none', 'Обычное состояние'), ('heat', 'Течка'), ('pregnant', 'Беременность'), ('lactating', 'Лактация')], default='none', help_text='Только для некастрированных самок', max_length=15, verbose_name='Репродуктивное состояние'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Самец'), ('female', 'Самка')], default='male', help_text='Пол питомца: male / female', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size_category',
            field=models.CharField(blank=True, choices=[('toy', 'Той (до 5 кг)'), ('small', 'Маленький (5-10 кг)'), ('medium', 'Средний (10-25 кг)'), ('large', 'Крупный (25-45 кг)'), ('giant', 'Гигантский (более 45 кг)')], help_text='Автозаполняется из породы или рассчитывается по весу/возрасту', max_length=20, null=True, verbose_name='Категория размера'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temperament',
            field=models.CharField(blank=True, choices=[('calm', 'Спокойный'), ('balanced', 'Уравновешенный'), ('active', 'Активный'), ('hyperactive', 'Гиперактивный')], help_text='Темперамент питомца (Этап 2)', max_length=20, null=True, verbose_name='Темперамент'),
        ),
        migrations.AddField(
            model_name='pet',
            name='yard_size',
            field=models.CharField(blank=True, choices=[('small', 'Маленький (до 100 м²)'), ('medium', 'Средний (100-500 м²)'), ('large', 'Большой (более 500 м²)')], help_text='Отображается только если has_yard=True', max_length=20, null=True, verbose_name='Размер двора'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='coat_type',
            field=models.CharField(choices=[('hairless', 'Бесшёрстная'), ('short', 'Короткая'), ('medium', 'Средняя'), ('long', 'Длинная'), ('wire', 'Жёсткая'), ('curly', 'Курчавая'), ('double', 'Двойная')], help_text='Для автозаполнения PetID', max_length=20, verbose_name='Тип шерсти'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название породы (рус)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название породы (англ)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание (рус)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size_category',
            field=models.CharField(choices=[('toy', 'Карликовый'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный'), ('giant', 'Гигантский')], db_index=True, help_text='Категория размера для автозаполнения PetID', max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='species',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], db_index=True, max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.CharField(choices=[('very_low', 'Очень низкая'), ('low', 'Низкая'), ('moderate', 'Умеренная'), ('high', 'Высокая'), ('very_high', 'Очень высокая')], default='moderate', max_length=20, verbose_name='Обучаемость'),
        ),
        migrations.AlterField(
            model_name='breedcare',
            name='care_category',
            field=models.CharField(choices=[('coat', 'Шерсть'), ('skin', 'Кожа'), ('ears', 'Уши'), ('eyes', 'Глаза'), ('respiratory', 'Дыхание'), ('dental', 'Зубы'), ('nails', 'Когти')], db_index=True, max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='breedcare',
            name='importance',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], db_index=True, max_length=20, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='breedcare',
            name='season',
            field=models.CharField(choices=[('all', 'Круглый год'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], default='all', max_length=20, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='breedhealth',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_health_records', to='pets.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='breedhealth',
            name='condition_type',
            field=models.CharField(choices=[('genetic', 'Генетическое'), ('congenital', 'Врожденное')], default='genetic', max_length=20),
        ),
        migrations.AlterField(
            model_name='breedhealth',
            name='prevalence_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Распространённость %'),
        ),
        migrations.AlterField(
            model_name='breedhealth',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], db_index=True, max_length=20, verbose_name='Тяжесть'),
        ),
        migrations.AlterField(
            model_name='breednutrition',
            name='calorie_density',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='breednutrition',
            name='common_allergens',
            field=models.JSONField(blank=True, default=list, verbose_name='Аллергены'),
        ),
        migrations.AlterField(
            model_name='breednutrition',
            name='diet_type',
            field=models.CharField(choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='breednutrition',
            name='protein_need',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('very_high', 'Очень высокая')], max_length=20, verbose_name='Потребность в белке'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(choices=[('very_low', 'Очень низкая'), ('low', 'Низкая'), ('moderate', 'Умеренная'), ('high', 'Высокая'), ('very_high', 'Очень высокая')], default='moderate', help_text='Уровень физической активности питомца', max_length=15, verbose_name='Уровень активности'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='behavioral_problems',
            field=models.JSONField(blank=True, default=list, help_text='Массив кодов проблем из BEHAVIORAL_PROBLEM_CHOICES', verbose_name='Поведенческие проблемы'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Есть дети в доме'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='has_yard',
            field=models.BooleanField(default=False, help_text='Зависит от housing_type', verbose_name='Есть двор'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Частный дом'), ('farm', 'Ферма/сельская местность'), ('outdoor', 'Вольерное содержание')], max_length=20, null=True, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='social_level',
            field=models.CharField(blank=True, choices=[('antisocial', 'Избегает контактов'), ('reserved', 'Сдержанный'), ('friendly', 'Дружелюбный'), ('very_social', 'Очень общительный')], help_text='Уровень социализации питомца (Этап 2)', max_length=20, null=True, verbose_name='Уровень социализации'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка')], help_text='Вид животного (собака, кошка, птица и т.д.)', max_length=50, verbose_name='Вид'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['species', 'name'], name='breeds_species_796cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['external_id'], name='breeds_externa_17691b_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['slug'], name='breeds_slug_daff52_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['size_category'], name='breeds_size_ca_203ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['coat_type'], name='breeds_coat_ty_7ee147_idx'),
        ),
        migrations.AddField(
            model_name='pethealthcondition',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_conditions', to='pets.healthcondition', verbose_name='Заболевание'),
        ),
        migrations.AddField(
            model_name='pethealthcondition',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_health_conditions', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='petfoodexclusion',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_exclusions', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='petfoodexclusion',
            name='related_allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_exclusions', to='pets.allergy', verbose_name='Связанная аллергия'),
        ),
        migrations.AddField(
            model_name='petallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_allergies', to='pets.allergy', verbose_name='Аллергия'),
        ),
        migrations.AddField(
            model_name='petallergy',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_allergies', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddIndex(
            model_name='nutritioncoefficient',
            index=models.Index(fields=['species', 'coefficient_type'], name='nutrition_c_species_d3865d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritioncoefficient',
            unique_together={('species', 'coefficient_type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='pethealthcondition',
            unique_together={('pet', 'condition')},
        ),
        migrations.AlterUniqueTogether(
            name='petfoodexclusion',
            unique_together={('pet', 'ingredient_code')},
        ),
        migrations.AlterUniqueTogether(
            name='petallergy',
            unique_together={('pet', 'allergy')},
        ),
    ]
