from django.db import migrations, models
import django.contrib.postgres.fields


MEDICATIONS = [
        {
            'code': 'apoquel',
            'name_trade': 'Апоквел',
            'name_active': 'Оклацитиниб',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аллергические дерматиты и зуд',
            'typical_frequency': ['once_daily', 'twice_daily'],
        },
        {
            'code': 'bravecto',
            'name_trade': 'Бравекто',
            'name_active': 'Флураланер',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['every_3_months'],
        },
        {
            'code': 'nexgard',
            'name_trade': 'НексГард',
            'name_active': 'Афоксоланер',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'simparica',
            'name_trade': 'Симпарика',
            'name_active': 'Сароланер',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'frontline',
            'name_trade': 'Фронтлайн',
            'name_active': 'Фипронил',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'metacam',
            'name_trade': 'Метакам',
            'name_active': 'Мелоксикам',
            'category': 'nsaid',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'gabapentin',
            'name_trade': 'Габапентин',
            'name_active': 'Габапентин',
            'category': 'analgesic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Болевой синдром',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'prednisolone',
            'name_trade': 'Преднизолон',
            'name_active': 'Преднизолон',
            'category': 'immunosuppressant',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Воспалительные и аутоиммунные состояния',
            'typical_frequency': ['varies'],
        },
        {
            'code': 'vetmedin',
            'name_trade': 'Ветмедин',
            'name_active': 'Пимобендан',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Сердечная недостаточность',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'fortekor',
            'name_trade': 'Фортекор',
            'name_active': 'Беназеприл',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Заболевания сердца',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'enroxil',
            'name_trade': 'Энроксил',
            'name_active': 'Энрофлоксацин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Бактериальные инфекции',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'baytril',
            'name_trade': 'Байтрил',
            'name_active': 'Энрофлоксацин',
            'category': 'antibiotic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Бактериальные инфекции',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'amoxiclav',
            'name_trade': 'Амоксиклав',
            'name_active': 'Амоксициллин + клавуланат',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Бактериальные инфекции дыхательных путей и кожи',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'amoxicillin',
            'name_trade': 'Амоксициллин',
            'name_active': 'Амоксициллин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Бактериальные инфекции',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'cephalexin',
            'name_trade': 'Цефалексин',
            'name_active': 'Цефалексин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Инфекции кожи и мочевыводящих путей',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'cefazolin',
            'name_trade': 'Цефазолин',
            'name_active': 'Цефазолин',
            'category': 'antibiotic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Тяжелые бактериальные инфекции',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'doxycycline',
            'name_trade': 'Доксициклин',
            'name_active': 'Доксициклин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Респираторные инфекции и инфекции кожи',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'clindamycin',
            'name_trade': 'Клиндамицин',
            'name_active': 'Клиндамицин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Инфекции мягких тканей и полости рта',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'metronidazole',
            'name_trade': 'Метронидазол',
            'name_active': 'Метронидазол',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Диарея и инфекции ЖКТ',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'tylosin',
            'name_trade': 'Тилозин',
            'name_active': 'Тилозин',
            'category': 'antibiotic',
            'form': 'other',
            'species': 'both',
            'indications': 'Хронические энтеропатии',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'marbocyl',
            'name_trade': 'Марбоцил',
            'name_active': 'Марбофлоксацин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Бактериальные инфекции',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'orbax',
            'name_trade': 'Орбакс',
            'name_active': 'Орбифлоксацин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Инфекции кожи и дыхательных путей',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'convenia',
            'name_trade': 'Конвения',
            'name_active': 'Цефовецин',
            'category': 'antibiotic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Инфекции кожи',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'synulox',
            'name_trade': 'Синулокс',
            'name_active': 'Амоксициллин + клавуланат',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Бактериальные инфекции',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'zeniquin',
            'name_trade': 'Зениквин',
            'name_active': 'Марбофлоксацин',
            'category': 'antibiotic',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Инфекции кожи и дыхательных путей',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'advantage',
            'name_trade': 'Адвантейдж',
            'name_active': 'Имидаклоприд',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Защита от блох',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'advantix',
            'name_trade': 'Адвантикс',
            'name_active': 'Имидаклоприд + перметрин',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'dog',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'advocate',
            'name_trade': 'Адвокат',
            'name_active': 'Имидаклоприд + моксидектин',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Эндо- и эктопаразиты',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'stronghold',
            'name_trade': 'Стронгхолд',
            'name_active': 'Селамектин',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Эндо- и эктопаразиты',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'revolution',
            'name_trade': 'Революция',
            'name_active': 'Селамектин',
            'category': 'antiparasitic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Эндо- и эктопаразиты',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'credelio',
            'name_trade': 'Кределио',
            'name_active': 'Лотиланер',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Защита от блох и клещей',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'comfortis',
            'name_trade': 'Комфортис',
            'name_active': 'Спиносад',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Защита от блох',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'sentinel',
            'name_trade': 'Сентинел',
            'name_active': 'Мильбемицин + луфенурон',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Профилактика паразитов',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'interceptor',
            'name_trade': 'Интерсептор',
            'name_active': 'Мильбемицин',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Профилактика гельминтозов',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'milbemax',
            'name_trade': 'Мильбемакс',
            'name_active': 'Мильбемицин + празиквантел',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Гельминтозы',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'drontal',
            'name_trade': 'Дронтал',
            'name_active': 'Празиквантел + пирантел',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Гельминтозы',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'prazitel',
            'name_trade': 'Празител',
            'name_active': 'Празиквантел + пирантел',
            'category': 'antiparasitic',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Гельминтозы',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'praziquantel',
            'name_trade': 'Празиквантел',
            'name_active': 'Празиквантел',
            'category': 'antiparasitic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Цестодозы',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'pyrantel',
            'name_trade': 'Пирантел',
            'name_active': 'Пирантел',
            'category': 'antiparasitic',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Нематодозы',
            'typical_frequency': ['monthly'],
        },
        {
            'code': 'panacur',
            'name_trade': 'Панакур',
            'name_active': 'Фенбендазол',
            'category': 'antiparasitic',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Гельминтозы',
            'typical_frequency': ['varies'],
        },
        {
            'code': 'fenbendazole',
            'name_trade': 'Фенбендазол',
            'name_active': 'Фенбендазол',
            'category': 'antiparasitic',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Гельминтозы',
            'typical_frequency': ['varies'],
        },
        {
            'code': 'alizin',
            'name_trade': 'Ализин',
            'name_active': 'Аглепристон',
            'category': 'hormonal',
            'form': 'injection',
            'species': 'dog',
            'indications': 'Прерывание нежелательной беременности',
            'typical_frequency': ['once'],
        },
        {
            'code': 'surolan',
            'name_trade': 'Суролан',
            'name_active': 'Миконазол + полимиксин + преднизолон',
            'category': 'dermatological',
            'form': 'drops',
            'species': 'both',
            'indications': 'Отиты и дерматиты',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'otodine',
            'name_trade': 'Отодин',
            'name_active': 'Хлоргексидин',
            'category': 'dermatological',
            'form': 'drops',
            'species': 'both',
            'indications': 'Гигиена ушей',
            'typical_frequency': ['weekly'],
        },
        {
            'code': 'easotic',
            'name_trade': 'Иазотик',
            'name_active': 'Гидрокортизон ацепонат',
            'category': 'dermatological',
            'form': 'drops',
            'species': 'dog',
            'indications': 'Отиты',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'posatex',
            'name_trade': 'Позатекс',
            'name_active': 'Орбифлоксацин + позаконазол + мометазон',
            'category': 'dermatological',
            'form': 'drops',
            'species': 'dog',
            'indications': 'Отиты',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'tresaderm',
            'name_trade': 'Трезадерм',
            'name_active': 'Тиабендазол + дексаметазон',
            'category': 'dermatological',
            'form': 'drops',
            'species': 'both',
            'indications': 'Отиты и дерматиты',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'dermavet',
            'name_trade': 'Дермавет',
            'name_active': 'Хлоргексидин',
            'category': 'dermatological',
            'form': 'spray',
            'species': 'both',
            'indications': 'Дерматиты',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'fuciderm',
            'name_trade': 'Фуцидерм',
            'name_active': 'Фузидиевая кислота + бетаметазон',
            'category': 'dermatological',
            'form': 'ointment',
            'species': 'both',
            'indications': 'Инфекции кожи',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'mupirocin',
            'name_trade': 'Мупироцин',
            'name_active': 'Мупироцин',
            'category': 'dermatological',
            'form': 'ointment',
            'species': 'both',
            'indications': 'Бактериальные инфекции кожи',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'chlorhexidine',
            'name_trade': 'Хлоргексидин',
            'name_active': 'Хлоргексидин',
            'category': 'dermatological',
            'form': 'spray',
            'species': 'both',
            'indications': 'Обработка кожи',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'silver_sulfadiazine',
            'name_trade': 'Серебра сульфадиазин',
            'name_active': 'Сульфадиазин серебра',
            'category': 'dermatological',
            'form': 'ointment',
            'species': 'both',
            'indications': 'Ожоги и раны',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'omeprazole',
            'name_trade': 'Омепразол',
            'name_active': 'Омепразол',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Гастрит и язвы',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'famotidine',
            'name_trade': 'Фамотидин',
            'name_active': 'Фамотидин',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Гастрит и кислотозависимые состояния',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'sucralfate',
            'name_trade': 'Сукральфат',
            'name_active': 'Сукральфат',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Язвенная болезнь',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'cerenia',
            'name_trade': 'Церения',
            'name_active': 'Маропитант',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Рвота и укачивание',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'metoclopramide',
            'name_trade': 'Метоклопрамид',
            'name_active': 'Метоклопрамид',
            'category': 'gastrointestinal',
            'form': 'injection',
            'species': 'both',
            'indications': 'Рвота и гастропарез',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'loperamide',
            'name_trade': 'Лоперамид',
            'name_active': 'Лоперамид',
            'category': 'gastrointestinal',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Диарея',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'lactulose',
            'name_trade': 'Лактулоза',
            'name_active': 'Лактулоза',
            'category': 'gastrointestinal',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Запоры и печеночная энцефалопатия',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'fortiflora',
            'name_trade': 'Фортифлора',
            'name_active': 'Пробиотики',
            'category': 'supplement',
            'form': 'other',
            'species': 'both',
            'indications': 'Поддержка ЖКТ',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'enterosgel',
            'name_trade': 'Энтеросгель',
            'name_active': 'Полиметилсилоксан',
            'category': 'supplement',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Интоксикации и диарея',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'smecta',
            'name_trade': 'Смекта',
            'name_active': 'Диосмектит',
            'category': 'supplement',
            'form': 'other',
            'species': 'both',
            'indications': 'Диарея',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'kaolin_pectin',
            'name_trade': 'Каолин + пектин',
            'name_active': 'Каолин + пектин',
            'category': 'supplement',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Диарея',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'enalapril',
            'name_trade': 'Эналаприл',
            'name_active': 'Эналаприл',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Сердечная недостаточность',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'pimobendan',
            'name_trade': 'Пимобендан',
            'name_active': 'Пимобендан',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Сердечная недостаточность',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'furosemide',
            'name_trade': 'Фуросемид',
            'name_active': 'Фуросемид',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Отёки, сердечная недостаточность',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'spironolactone',
            'name_trade': 'Спиронолактон',
            'name_active': 'Спиронолактон',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Сердечная недостаточность',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'atenolol',
            'name_trade': 'Атенолол',
            'name_active': 'Атенолол',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аритмии',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'diltiazem',
            'name_trade': 'Дилтиазем',
            'name_active': 'Дилтиазем',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Гипертрофическая кардиомиопатия',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'amlodipine',
            'name_trade': 'Амлодипин',
            'name_active': 'Амлодипин',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Артериальная гипертензия',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'digoxin',
            'name_trade': 'Дигоксин',
            'name_active': 'Дигоксин',
            'category': 'cardiac',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Сердечная недостаточность',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'carprofen',
            'name_trade': 'Карпрофен',
            'name_active': 'Карпрофен',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'rimadyl',
            'name_trade': 'Римадил',
            'name_active': 'Карпрофен',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'meloxicam',
            'name_trade': 'Мелоксикам',
            'name_active': 'Мелоксикам',
            'category': 'nsaid',
            'form': 'suspension',
            'species': 'both',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'robenacoxib',
            'name_trade': 'Робенакоксиб',
            'name_active': 'Робенакоксиб',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'onsior',
            'name_trade': 'Онсиор',
            'name_active': 'Робенакоксиб',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'deramaxx',
            'name_trade': 'Дерамакс',
            'name_active': 'Деракоксиб',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'firocoxib',
            'name_trade': 'Фирококсиб',
            'name_active': 'Фирококсиб',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'previcox',
            'name_trade': 'Превикокс',
            'name_active': 'Фирококсиб',
            'category': 'nsaid',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Боль и воспаление',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'tramadol',
            'name_trade': 'Трамадол',
            'name_active': 'Трамадол',
            'category': 'analgesic',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Болевой синдром',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'buprenorphine',
            'name_trade': 'Бупренорфин',
            'name_active': 'Бупренорфин',
            'category': 'analgesic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Болевой синдром',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'butorphanol',
            'name_trade': 'Буторфанол',
            'name_active': 'Буторфанол',
            'category': 'analgesic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Болевой синдром',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'lidocaine',
            'name_trade': 'Лидокаин',
            'name_active': 'Лидокаин',
            'category': 'analgesic',
            'form': 'injection',
            'species': 'both',
            'indications': 'Местная анестезия',
            'typical_frequency': ['once'],
        },
        {
            'code': 'insulin_vetsulin',
            'name_trade': 'Ветсулин',
            'name_active': 'Инсулин',
            'category': 'hormonal',
            'form': 'injection',
            'species': 'both',
            'indications': 'Сахарный диабет',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'insulin_glargine',
            'name_trade': 'Инсулин гларгин',
            'name_active': 'Инсулин гларгин',
            'category': 'hormonal',
            'form': 'injection',
            'species': 'cat',
            'indications': 'Сахарный диабет',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'levothyroxine',
            'name_trade': 'Левотироксин',
            'name_active': 'Левотироксин',
            'category': 'hormonal',
            'form': 'tablets',
            'species': 'dog',
            'indications': 'Гипотиреоз',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'methimazole',
            'name_trade': 'Метимазол',
            'name_active': 'Тиамазол',
            'category': 'hormonal',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Гипертиреоз',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'cabergoline',
            'name_trade': 'Каберголин',
            'name_active': 'Каберголин',
            'category': 'hormonal',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Галакторея, ложная беременность',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'desmopressin',
            'name_trade': 'Десмопрессин',
            'name_active': 'Десмопрессин',
            'category': 'hormonal',
            'form': 'drops',
            'species': 'both',
            'indications': 'Несахарный диабет',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'trilostane',
            'name_trade': 'Трилостан',
            'name_active': 'Трилостан',
            'category': 'hormonal',
            'form': 'other',
            'species': 'dog',
            'indications': 'Синдром Кушинга',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'vetoryl',
            'name_trade': 'Веторил',
            'name_active': 'Трилостан',
            'category': 'hormonal',
            'form': 'other',
            'species': 'dog',
            'indications': 'Синдром Кушинга',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'altrenogest',
            'name_trade': 'Альтреногест',
            'name_active': 'Альтреногест',
            'category': 'hormonal',
            'form': 'suspension',
            'species': 'dog',
            'indications': 'Контроль репродуктивного цикла',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'cetirizine',
            'name_trade': 'Цетиризин',
            'name_active': 'Цетиризин',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аллергии',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'loratadine',
            'name_trade': 'Лоратадин',
            'name_active': 'Лоратадин',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аллергии',
            'typical_frequency': ['once_daily'],
        },
        {
            'code': 'chlorpheniramine',
            'name_trade': 'Хлорфенирамин',
            'name_active': 'Хлорфенирамин',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'cat',
            'indications': 'Аллергии',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'hydroxyzine',
            'name_trade': 'Гидроксизин',
            'name_active': 'Гидроксизин',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аллергии и зуд',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'diphenhydramine',
            'name_trade': 'Дифенгидрамин',
            'name_active': 'Дифенгидрамин',
            'category': 'antihistamine',
            'form': 'tablets',
            'species': 'both',
            'indications': 'Аллергии',
            'typical_frequency': ['twice_daily'],
        },
        {
            'code': 'tobramycin',
            'name_trade': 'Тобрамицин',
            'name_active': 'Тобрамицин',
            'category': 'ophthalmic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Глазные инфекции',
            'typical_frequency': ['three_times_daily'],
        },
        {
            'code': 'tobradex',
            'name_trade': 'Тобрадекс',
            'name_active': 'Тобрамицин + дексаметазон',
            'category': 'ophthalmic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Глазные инфекции и воспаление',
            'typical_frequency': ['three_times_daily'],
        },
        {
            'code': 'ofloxacin',
            'name_trade': 'Офлоксацин',
            'name_active': 'Офлоксацин',
            'category': 'ophthalmic',
            'form': 'drops',
            'species': 'both',
            'indications': 'Глазные инфекции',
            'typical_frequency': ['three_times_daily'],
        },
    ]

def seed_medications(apps, schema_editor):
    Medication = apps.get_model('pets', 'Medication')
    PetMedication = apps.get_model('pets', 'PetMedication')

    for item in MEDICATIONS:
        Medication.objects.update_or_create(code=item['code'], defaults=item)

    existing_codes = (
        PetMedication.objects.exclude(medication_code__isnull=True)
        .values_list('medication_code', flat=True)
        .distinct()
    )
    for code in existing_codes:
        if not Medication.objects.filter(code=code).exists():
            Medication.objects.create(
                code=code,
                name_trade=code,
                name_active=code,
                category='other',
                form='other',
                species='both',
                indications='Не указано',
                typical_frequency=[],
                notes='Добавлено автоматически из существующих записей.',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_create_vaccines_and_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код препарата')),
                ('name_trade', models.CharField(max_length=200, verbose_name='Торговое название')),
                ('name_active', models.CharField(max_length=200, verbose_name='Действующее вещество')),
                ('category', models.CharField(choices=[('antiparasitic', 'Антипаразитарные'), ('antihistamine', 'Антигистаминные'), ('antibiotic', 'Антибиотики'), ('nsaid', 'НПВС'), ('analgesic', 'Обезболивающие'), ('cardiac', 'Сердечные'), ('gastrointestinal', 'ЖКТ'), ('dermatological', 'Дерматологические'), ('ophthalmic', 'Офтальмологические'), ('hormonal', 'Гормональные'), ('immunosuppressant', 'Иммунодепрессанты'), ('supplement', 'Добавки'), ('other', 'Другое')], max_length=30, verbose_name='Категория')),
                ('form', models.CharField(choices=[('tablets', 'Таблетки'), ('drops', 'Капли'), ('injection', 'Инъекции'), ('ointment', 'Мазь'), ('suspension', 'Суспензия'), ('spray', 'Спрей'), ('other', 'Другое')], max_length=20, verbose_name='Форма выпуска')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('both', 'Оба')], max_length=10, verbose_name='Вид')),
                ('indications', models.TextField(verbose_name='Показания')),
                ('contraindications', models.TextField(blank=True, verbose_name='Противопоказания')),
                ('side_effects', models.TextField(blank=True, verbose_name='Побочные эффекты')),
                ('dosage_info', models.JSONField(blank=True, null=True, verbose_name='Информация о дозировке')),
                ('typical_frequency', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Типичная периодичность')),
                ('typical_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Типичная длительность (дни)')),
                ('interactions', models.TextField(blank=True, verbose_name='Взаимодействия')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['species', 'name_trade'],
            },
        ),
        migrations.RunPython(seed_medications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='petmedication',
            name='medication_code',
            field=models.ForeignKey(db_column='medication_code', on_delete=models.deletion.PROTECT, related_name='pet_medications', to='pets.medication', verbose_name='Код препарата'),
        ),
    ]
