# Generated by Django 5.1.5 on 2026-02-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_create_medications_and_fk'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
-- Функция автозаполнения профиля питомца
CREATE OR REPLACE FUNCTION pet_autofill()
RETURNS TRIGGER AS $$
DECLARE
    breed_record RECORD;
    calculated_size VARCHAR(20);
    calculated_bcs INTEGER;
    ideal_weight DECIMAL(5,2);
    weight_ratio DECIMAL(10,4);
    age_months INTEGER;
    base_activity VARCHAR(20);
    weight_min DECIMAL(5,2);
    weight_max DECIMAL(5,2);
    growth_factor DECIMAL(10,4);
    estimated_adult_weight DECIMAL(10,4);
BEGIN
    -- Возраст в месяцах (если известна дата рождения)
    IF NEW.date_of_birth IS NOT NULL THEN
        age_months := (EXTRACT(YEAR FROM AGE(CURRENT_DATE, NEW.date_of_birth))::INTEGER * 12)
            + EXTRACT(MONTH FROM AGE(CURRENT_DATE, NEW.date_of_birth))::INTEGER;
    END IF;

    -- Если есть порода, получаем данные из breeds
    IF NEW.breed_id IS NOT NULL THEN
        SELECT 
            size_category,
            coat_type,
            base_activity_level,
            weight_male_min,
            weight_male_max,
            weight_female_min,
            weight_female_max
        INTO breed_record
        FROM breeds
        WHERE id = NEW.breed_id;
        
        -- Автозаполнение size_category из породы (только если NULL)
        IF NEW.size_category IS NULL AND breed_record.size_category IS NOT NULL THEN
            NEW.size_category := breed_record.size_category;
        END IF;
        
        -- Автозаполнение coat_type из породы (только если NULL)
        IF NEW.coat_type IS NULL AND breed_record.coat_type IS NOT NULL THEN
            NEW.coat_type := breed_record.coat_type;
        END IF;
        
        -- Автозаполнение ideal_weight_kg из породы (только если NULL)
        IF NEW.ideal_weight_kg IS NULL THEN
            weight_min := COALESCE(
                CASE WHEN NEW.sex = 'female' THEN breed_record.weight_female_min END,
                CASE WHEN NEW.sex = 'male' THEN breed_record.weight_male_min END,
                breed_record.weight_female_min,
                breed_record.weight_male_min
            );
            weight_max := COALESCE(
                CASE WHEN NEW.sex = 'female' THEN breed_record.weight_female_max END,
                CASE WHEN NEW.sex = 'male' THEN breed_record.weight_male_max END,
                breed_record.weight_female_max,
                breed_record.weight_male_max
            );

            IF weight_min IS NOT NULL AND weight_max IS NOT NULL THEN
                ideal_weight := (weight_min + weight_max) / 2;
                -- Для щенков/котят корректируем ожидаемый вес
                IF age_months IS NOT NULL AND age_months < 12 THEN
                    growth_factor := POWER(age_months / 12.0, 0.75);
                    ideal_weight := ideal_weight * growth_factor;
                END IF;
            END IF;
            
            IF ideal_weight IS NOT NULL THEN
                NEW.ideal_weight_kg := ROUND(ideal_weight, 1);
            END IF;
        END IF;
        
        -- Автозаполнение activity_level из породы (только если NULL)
        IF NEW.activity_level IS NULL AND breed_record.base_activity_level IS NOT NULL THEN
            base_activity := breed_record.base_activity_level;

            -- Корректировка по возрасту
            IF age_months IS NOT NULL THEN
                IF NEW.species = 'dog' THEN
                    IF age_months < 12 THEN
                        IF base_activity = 'very_low' THEN base_activity := 'low';
                        ELSIF base_activity = 'low' THEN base_activity := 'moderate';
                        END IF;
                    ELSIF age_months >= 84 THEN
                        IF base_activity = 'very_high' THEN base_activity := 'high';
                        ELSIF base_activity = 'high' THEN base_activity := 'moderate';
                        END IF;
                    END IF;
                ELSIF NEW.species = 'cat' THEN
                    IF age_months < 12 THEN
                        IF base_activity = 'very_low' THEN base_activity := 'low';
                        ELSIF base_activity = 'low' THEN base_activity := 'moderate';
                        END IF;
                    ELSIF age_months >= 120 THEN
                        IF base_activity = 'very_high' THEN base_activity := 'high';
                        ELSIF base_activity = 'high' THEN base_activity := 'moderate';
                        END IF;
                    END IF;
                END IF;
            END IF;

            NEW.activity_level := base_activity;
        END IF;
        
    ELSE
        -- Дворняга (breed_id = NULL)
        
        -- Определение размера по весу и возрасту (только если NULL и есть вес)
        IF NEW.size_category IS NULL AND NEW.weight IS NOT NULL THEN
            IF age_months IS NULL THEN
                age_months := 24;
            END IF;

            IF NEW.species = 'cat' THEN
                -- Кошки: рост завершается к 12 месяцам
                IF age_months < 12 THEN
                    growth_factor := (12.0 / GREATEST(age_months, 1)) * 0.7;
                    estimated_adult_weight := NEW.weight * growth_factor;
                ELSE
                    estimated_adult_weight := NEW.weight;
                END IF;

                IF estimated_adult_weight < 3 THEN
                    calculated_size := 'small';
                ELSIF estimated_adult_weight < 6 THEN
                    calculated_size := 'medium';
                ELSE
                    calculated_size := 'large';
                END IF;
            ELSIF NEW.species = 'dog' THEN
                IF age_months < 3 THEN
                    growth_factor := 4.0;
                ELSIF age_months < 6 THEN
                    growth_factor := 3.0;
                ELSIF age_months < 9 THEN
                    growth_factor := 2.0;
                ELSIF age_months < 12 THEN
                    growth_factor := 1.5;
                ELSIF age_months < 18 THEN
                    growth_factor := 1.2;
                ELSE
                    growth_factor := 1.0;
                END IF;

                estimated_adult_weight := NEW.weight * growth_factor;

                IF estimated_adult_weight < 5 THEN
                    calculated_size := 'toy';
                ELSIF estimated_adult_weight < 10 THEN
                    calculated_size := 'small';
                ELSIF estimated_adult_weight < 25 THEN
                    calculated_size := 'medium';
                ELSIF estimated_adult_weight < 45 THEN
                    calculated_size := 'large';
                ELSE
                    calculated_size := 'giant';
                END IF;
            END IF;
            
            IF calculated_size IS NOT NULL THEN
                NEW.size_category := calculated_size;
            END IF;
        END IF;
        
        -- Активность по умолчанию для дворняг (только если NULL)
        IF NEW.activity_level IS NULL THEN
            NEW.activity_level := 'moderate';
        END IF;
    END IF;
    
    -- Расчёт BCS (Body Condition Score) если есть вес и идеальный вес (только если NULL)
    IF NEW.body_condition_score IS NULL AND NEW.weight IS NOT NULL AND NEW.ideal_weight_kg IS NOT NULL THEN
        weight_ratio := NEW.weight / NEW.ideal_weight_kg;
        
        IF weight_ratio < 0.85 THEN
            calculated_bcs := GREATEST(1, ROUND(5 * weight_ratio)::INTEGER);
        ELSIF weight_ratio < 1.10 THEN
            calculated_bcs := 5;
        ELSIF weight_ratio < 1.20 THEN
            calculated_bcs := 6;
        ELSIF weight_ratio < 1.30 THEN
            calculated_bcs := 7;
        ELSIF weight_ratio < 1.40 THEN
            calculated_bcs := 8;
        ELSE
            calculated_bcs := 9;
        END IF;
        
        NEW.body_condition_score := calculated_bcs;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Создание триггера
CREATE TRIGGER pet_autofill_trigger
    BEFORE INSERT ON pets
    FOR EACH ROW
    EXECUTE FUNCTION pet_autofill();
            """,
            reverse_sql="""
-- Удаление триггера и функции
DROP TRIGGER IF EXISTS pet_autofill_trigger ON pets;
DROP FUNCTION IF EXISTS pet_autofill();
            """
        ),
    ]
