# Generated by Django 5.1.5 on 2026-02-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_create_medications_and_fk'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
-- Функция автозаполнения профиля питомца
CREATE OR REPLACE FUNCTION pet_autofill()
RETURNS TRIGGER AS $$
DECLARE
    breed_record RECORD;
    calculated_size VARCHAR(20);
    calculated_bcs INTEGER;
    ideal_weight DECIMAL(5,2);
    weight_ratio DECIMAL(10,4);
BEGIN
    -- Если есть порода, получаем данные из breeds
    IF NEW.breed_id IS NOT NULL THEN
        SELECT 
            size_category,
            coat_type,
            base_activity_level,
            weight_male_min,
            weight_male_max,
            weight_female_min,
            weight_female_max
        INTO breed_record
        FROM breeds
        WHERE id = NEW.breed_id;
        
        -- Автозаполнение size_category из породы (только если NULL)
        IF NEW.size_category IS NULL AND breed_record.size_category IS NOT NULL THEN
            NEW.size_category := breed_record.size_category;
        END IF;
        
        -- Автозаполнение coat_type из породы (только если NULL)
        IF NEW.coat_type IS NULL AND breed_record.coat_type IS NOT NULL THEN
            NEW.coat_type := breed_record.coat_type;
        END IF;
        
        -- Автозаполнение ideal_weight_kg из породы (только если NULL)
        IF NEW.ideal_weight_kg IS NULL THEN
            IF NEW.sex = 'female' AND breed_record.weight_female_min IS NOT NULL AND breed_record.weight_female_max IS NOT NULL THEN
                ideal_weight := (breed_record.weight_female_min + breed_record.weight_female_max) / 2;
            ELSIF NEW.sex = 'male' AND breed_record.weight_male_min IS NOT NULL AND breed_record.weight_male_max IS NOT NULL THEN
                ideal_weight := (breed_record.weight_male_min + breed_record.weight_male_max) / 2;
            ELSIF breed_record.weight_male_min IS NOT NULL AND breed_record.weight_male_max IS NOT NULL THEN
                -- Fallback на мужской вес
                ideal_weight := (breed_record.weight_male_min + breed_record.weight_male_max) / 2;
            END IF;
            
            IF ideal_weight IS NOT NULL THEN
                NEW.ideal_weight_kg := ROUND(ideal_weight, 1);
            END IF;
        END IF;
        
        -- Автозаполнение activity_level из породы (только если NULL)
        IF NEW.activity_level IS NULL AND breed_record.base_activity_level IS NOT NULL THEN
            NEW.activity_level := breed_record.base_activity_level;
        END IF;
        
    ELSE
        -- Дворняга (breed_id = NULL)
        
        -- Определение размера по весу (только если NULL и есть вес)
        IF NEW.size_category IS NULL AND NEW.weight IS NOT NULL THEN
            IF NEW.species = 'cat' THEN
                -- Кошки: small < 4, medium 4-6, large >= 6
                IF NEW.weight < 4 THEN
                    calculated_size := 'small';
                ELSIF NEW.weight < 6 THEN
                    calculated_size := 'medium';
                ELSE
                    calculated_size := 'large';
                END IF;
            ELSIF NEW.species = 'dog' THEN
                -- Собаки: toy < 5, small 5-10, medium 10-25, large 25-45, giant >= 45
                IF NEW.weight < 5 THEN
                    calculated_size := 'toy';
                ELSIF NEW.weight < 10 THEN
                    calculated_size := 'small';
                ELSIF NEW.weight < 25 THEN
                    calculated_size := 'medium';
                ELSIF NEW.weight < 45 THEN
                    calculated_size := 'large';
                ELSE
                    calculated_size := 'giant';
                END IF;
            END IF;
            
            IF calculated_size IS NOT NULL THEN
                NEW.size_category := calculated_size;
            END IF;
        END IF;
        
        -- Активность по умолчанию для дворняг (только если NULL)
        IF NEW.activity_level IS NULL THEN
            NEW.activity_level := 'moderate';
        END IF;
    END IF;
    
    -- Расчёт BCS (Body Condition Score) если есть вес и идеальный вес (только если NULL)
    IF NEW.body_condition_score IS NULL AND NEW.weight IS NOT NULL AND NEW.ideal_weight_kg IS NOT NULL THEN
        weight_ratio := NEW.weight / NEW.ideal_weight_kg;
        
        IF weight_ratio < 0.85 THEN
            calculated_bcs := GREATEST(1, ROUND(5 * weight_ratio)::INTEGER);
        ELSIF weight_ratio < 1.10 THEN
            calculated_bcs := 5;
        ELSIF weight_ratio < 1.20 THEN
            calculated_bcs := 6;
        ELSIF weight_ratio < 1.30 THEN
            calculated_bcs := 7;
        ELSIF weight_ratio < 1.40 THEN
            calculated_bcs := 8;
        ELSE
            calculated_bcs := 9;
        END IF;
        
        NEW.body_condition_score := calculated_bcs;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Создание триггера
CREATE TRIGGER pet_autofill_trigger
    BEFORE INSERT OR UPDATE ON pets
    FOR EACH ROW
    EXECUTE FUNCTION pet_autofill();
            """,
            reverse_sql="""
-- Удаление триггера и функции
DROP TRIGGER IF EXISTS pet_autofill_trigger ON pets;
DROP FUNCTION IF EXISTS pet_autofill();
            """
        ),
    ]
