# Generated by Django 4.2.8 on 2025-12-20 13:00

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор платежа', max_length=36, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('shop_order', 'Заказ товаров'), ('course', 'Покупка курса'), ('subscription', 'Подписка')], max_length=20, verbose_name='Тип платежа')),
                ('object_id', models.CharField(help_text='ID связанного объекта (заказа, курса и т.д.)', max_length=36, verbose_name='ID объекта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('failed', 'Неудачный'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('cash', 'Наличными'), ('digital_wallet', 'Электронный кошелёк')], default='card', max_length=20, verbose_name='Метод оплаты')),
                ('external_payment_id', models.CharField(blank=True, help_text='ID платежа во внешней системе (ЮKassa, Stripe и т.д.)', max_length=100, null=True, verbose_name='Внешний ID платежа')),
                ('payment_gateway', models.CharField(blank=True, help_text='Название платёжного шлюза (yookassa, stripe и т.д.)', max_length=50, null=True, verbose_name='Платёжный шлюз')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация о платеже', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Когда платеж был успешно завершён', null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'), models.Index(fields=['payment_type', 'status'], name='payments_payment_ebcbf8_idx'), models.Index(fields=['external_payment_id'], name='payments_externa_46a519_idx'), models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx')],
            },
        ),
    ]
