# Generated by Django 4.2.8 on 2025-12-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('shop_order', 'Заказ товаров'), ('course', 'Покупка курса'), ('subscription', 'Подписка'), ('unified_checkout', 'Единый чек аут (товары + курсы)')], max_length=20, verbose_name='Тип платежа'),
        ),
    ]
