# Generated by Django 4.2.8 on 2025-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='animal',
            field=models.CharField(choices=[('dog', 'Для собак'), ('cat', 'Для кошек')], db_index=True, default='dog', max_length=10, verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Корм'), ('pharmacy', 'Ветаптека'), ('ammunition', 'Амуниция'), ('care', 'Средства по уходу'), ('transport', 'Транспортировка'), ('toys', 'Игрушки')], db_index=True, default='food', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID группы'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list, verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('canned', 'Консервы'), ('pouch', 'Паучи'), ('pate', 'Паштет'), ('holistic', 'Холистик'), ('diet', 'Диетический'), ('hypoallergenic', 'Гипоаллергенный'), ('antiparasite', 'Средства от паразитов'), ('leashes', 'Поводки'), ('collars', 'Ошейники'), ('harnesses', 'Шлейки'), ('muzzles', 'Намордники'), ('clickers', 'Кликеры'), ('retractable', 'Рулетки'), ('lights', 'Подсветки'), ('multiboxes', 'Мультибоксы'), ('enclosures', 'Клетки'), ('pads', 'Пелёнки'), ('general', 'Общее')], db_index=True, max_length=30, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['animal', 'category'], name='products_animal_50c403_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['animal', 'category', 'subcategory'], name='products_animal_0efe76_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='products_vendor_8596a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_price_fe467e_idx'),
        ),
    ]
