# Generated by Django 4.2.8 on 2025-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_url_remove_product_pet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL товара'),
        ),
    ]
