# Generated by Django 4.2.8 on 2025-12-20 11:29

import core.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор корзины', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор заказа', max_length=36, primary_key=True, serialize=False),
        ),
    ]
