# Generated by Django 4.2.8 on 2025-12-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_usercourse_unique_together_usercourse_pet_and_more'),
        ('pets', '0003_alter_pet_breed_alter_pet_created_at_and_more'),
        ('shop', '0007_add_course_fields_to_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='Подтверждение согласия с условиями использования для курсов', verbose_name='Согласие с условиями'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Питомец, для которого приобретается курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Название товара/курса'),
        ),
    ]
