# Generated by Django 4.2.8 on 2025-12-22 17:43

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_orderitem_course_orderitem_disclaimer_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('reservation_type', models.CharField(choices=[('product', 'Резервирование товара'), ('course', 'Резервирование курса')], max_length=20)),
                ('object_id', models.CharField(max_length=36)),
                ('pet_id', models.CharField(blank=True, max_length=36, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='reservation_user_id_d939c4_idx'), models.Index(fields=['reservation_type', 'object_id'], name='reservation_reserva_cfad2d_idx'), models.Index(fields=['expires_at'], name='reservation_expires_9dca17_idx')],
            },
        ),
    ]
