# Generated by Django 4.2.8 on 2025-12-24 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_reservation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Сумма товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая сумма'),
        ),
    ]
