# Generated by Django 4.2.8 on 2025-12-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_subtotal_amount_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения срока оплаты заказа. Если оплата не произведена до этого времени, заказ будет отменен и товары возвращены на склад.', null=True, verbose_name='Истекает (время оплаты)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('expired', 'Истёк срок оплаты')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
