# Generated by Django 4.2.8 on 2025-12-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_breed_alter_pet_created_at_and_more'),
        ('training', '0005_auto_20251224_1835'),
        ('shop', '0011_order_expires_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Питомец, для которого приобретается курс (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар'),
        ),
    ]
