# Generated by Django 4.2.8 on 2026-01-09 08:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_order_count_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('partially_delivered', 'Частично доставлен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('expired', 'Истёк срок оплаты')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list, help_text='Массив URL изображений товара', validators=[core.validators.validate_url_list], verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры товара в формате словаря', validators=[core.validators.validate_product_params], verbose_name='Параметры'),
        ),
    ]
