# Generated by Django 5.1.5 on 2026-01-12 20:00

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_product_order_count_return'),
    ]

    operations = [
        # Из 0014_add_partially_delivered_status: изменение статуса заказов
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('partially_delivered', 'Частично доставлен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('expired', 'Истёк срок оплаты')], default='pending', max_length=20, verbose_name='Статус'),
        ),

        # Из обеих миграций: изменения полей product (берём из любой)
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list, help_text='Массив URL изображений товара', validators=[core.validators.validate_url_list], verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные параметры товара в формате словаря', validators=[core.validators.validate_product_params], verbose_name='Параметры'),
        ),

        # Из 0014_add_nutrition_params: создание моделей аналитики
        migrations.CreateModel(
            name='ChartSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict, help_text='Текущее состояние конфигурации')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('saved', 'Сохраненная'), ('expired', 'Истекшая')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Время истечения сессии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_chart_sessions',
                'indexes': [models.Index(fields=['user', '-last_activity_at'], name='analytics_c_user_id_b95313_idx'), models.Index(fields=['status', 'expires_at'], name='analytics_c_status_c2d049_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название графика', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание графика')),
                ('chart_type', models.CharField(choices=[('line', 'Линейный график'), ('bar', 'Столбчатая диаграмма'), ('area', 'Диаграмма с областями'), ('scatter', 'Точечная диаграмма'), ('bubble', 'Пузырьковая диаграмма'), ('pie', 'Круговая диаграмма'), ('combo', 'Комбинированный график'), ('heatmap', 'Тепловая карта')], default='line', help_text='Основной тип графика', max_length=20)),
                ('canvas_config', models.JSONField(default=dict, help_text='Настройки холста (ширина, высота, margins)')),
                ('x_axis_config', models.JSONField(default=dict, help_text='Конфигурация оси X')),
                ('y_axis_config', models.JSONField(default=dict, help_text='Конфигурация оси Y (или осей Y для multi-axis)')),
                ('data_layers', models.JSONField(default=list, help_text='Конфигурация слоев данных')),
                ('filters_config', models.JSONField(default=dict, help_text='Настройки фильтров')),
                ('segment_config', models.JSONField(default=dict, help_text='Настройки сегментации данных')),
                ('style_config', models.JSONField(default=dict, help_text='Настройки стилей и цветов')),
                ('legend_config', models.JSONField(default=dict, help_text='Настройки легенды')),
                ('interaction_config', models.JSONField(default=dict, help_text='Настройки интерактивности (tooltips, drill-down)')),
                ('is_template', models.BooleanField(default=False, help_text='Является ли конфигурация шаблоном')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли шаблон всем пользователям')),
                ('category', models.CharField(blank=True, help_text='Категория шаблона', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Теги для поиска')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Количество использований')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Последнее использование', null=True)),
                ('preview_image', models.ImageField(blank=True, help_text='Превью изображение графика', null=True, upload_to='chart-previews/')),
                ('export_formats', models.JSONField(default=list, help_text='Доступные форматы экспорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Версия конфигурации')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_charts', to=settings.AUTH_USER_MODEL)),
                ('parent_config', models.ForeignKey(blank=True, help_text='Родительская конфигурация (для версий)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_configs', to='shop.chartconfig')),
            ],
            options={
                'db_table': 'analytics_chart_configs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', '-updated_at'], name='analytics_c_created_62186a_idx'), models.Index(fields=['is_template', 'is_public'], name='analytics_c_is_temp_942135_idx'), models.Index(fields=['category'], name='analytics_c_categor_593c43_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view_metrics', 'Просмотр метрик'), ('create_chart', 'Создание графика'), ('save_config', 'Сохранение конфигурации'), ('export_data', 'Экспорт данных'), ('share_template', 'Поделиться шаблоном')], help_text='Тип действия', max_length=50)),
                ('resource_type', models.CharField(help_text='Тип ресурса (chart, metric, template, etc.)', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID ресурса', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Дополнительная информация о действии')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent браузера')),
                ('execution_time', models.FloatField(blank=True, help_text='Время выполнения запроса (секунды)', null=True)),
                ('data_points', models.PositiveIntegerField(default=0, help_text='Количество точек данных')),
                ('success', models.BooleanField(default=True, help_text='Успешность операции')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_l_user_id_f36204_idx'), models.Index(fields=['action', '-timestamp'], name='analytics_l_action_8ed59c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='analytics_l_resourc_646d1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticMetric',
            fields=[
                ('id', models.CharField(help_text='Уникальный идентификатор метрики', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Человеко-понятное название метрики', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Подробное описание метрики')),
                ('category', models.CharField(help_text='Категория метрики (users, pets, orders, courses, etc.)', max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text='Подкатегория для дополнительной группировки', max_length=100)),
                ('data_type', models.CharField(choices=[('integer', 'Целое число'), ('decimal', 'Десятичное число'), ('string', 'Строка'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('boolean', 'Логический'), ('json', 'JSON')], help_text='Тип данных метрики', max_length=20)),
                ('default_aggregation', models.CharField(choices=[('count', 'COUNT'), ('sum', 'SUM'), ('avg', 'AVG'), ('min', 'MIN'), ('max', 'MAX'), ('stddev', 'STDDEV'), ('variance', 'VARIANCE')], default='count', help_text='Агрегация по умолчанию', max_length=20)),
                ('available_aggregations', models.JSONField(default=list, help_text='Список доступных типов агрегации')),
                ('table_name', models.CharField(help_text='Имя таблицы в базе данных', max_length=100)),
                ('field_name', models.CharField(help_text='Имя поля в таблице', max_length=100)),
                ('sql_template', models.TextField(blank=True, help_text='SQL шаблон для сложных вычислений')),
                ('related_fields', models.JSONField(default=list, help_text='Связанные поля для JOIN операций')),
                ('filter_fields', models.JSONField(default=list, help_text='Поля, доступные для фильтрации')),
                ('dimension_fields', models.JSONField(default=list, help_text='Поля, доступные для группировки (оси X)')),
                ('units', models.CharField(blank=True, help_text='Единицы измерения', max_length=50)),
                ('format_pattern', models.CharField(blank=True, help_text='Шаблон форматирования (для чисел, дат)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли метрика')),
                ('is_system', models.BooleanField(default=False, help_text='Системная метрика (нельзя удалять)')),
                ('cache_ttl', models.PositiveIntegerField(default=300, help_text='Время жизни кэша в секундах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_metrics',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='analytics_m_categor_89f816_idx'), models.Index(fields=['table_name', 'field_name'], name='analytics_m_table_n_f36bbe_idx')],
            },
        ),
    ]
