# Generated by Django 4.2.8 on 2026-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_merge_20260112_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='Список аллергенов в составе: ["chicken", "beef", "fish", ...]', verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Приоритет бренда для рекомендаций (0-10)', verbose_name='Приоритет бренда'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_group',
            field=models.CharField(choices=[('regular', 'Обычный'), ('hypoallergenic', 'Гипоаллергенный'), ('therapeutic_renal', 'Лечебный: почки'), ('therapeutic_diabetic', 'Лечебный: диабет'), ('therapeutic_digestive', 'Лечебный: ЖКТ'), ('therapeutic_weight', 'Лечебный: вес'), ('therapeutic_urinary', 'Лечебный: МКБ')], default='regular', help_text='Группа для определения совместимости с другими кормами', max_length=30, verbose_name='Группа совместимости'),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal_per_100g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Калорийность продукта для расчёта порций. Обязательно для кормов.', max_digits=6, null=True, verbose_name='Калорийность (ккал/100г)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальный возраст питомца в месяцах. NULL = без ограничений', null=True, verbose_name='Макс. возраст (мес.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Минимальный возраст питомца в месяцах', null=True, verbose_name='Мин. возраст (мес.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_ash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание золы в %', max_digits=5, null=True, verbose_name='Зола (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание жира в %', max_digits=5, null=True, verbose_name='Жир (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание клетчатки в %', max_digits=5, null=True, verbose_name='Клетчатка (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_moisture',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание влаги в %', max_digits=5, null=True, verbose_name='Влажность (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание белка в %', max_digits=5, null=True, verbose_name='Белок (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_size',
            field=models.CharField(choices=[('all', 'Все размеры'), ('toy', 'Той'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный'), ('giant', 'Гигантский')], default='all', help_text='Для какого размера питомца предназначен корм', max_length=10, verbose_name='Целевой размер'),
        ),
    ]
