# Generated by Django 4.2.8 on 2026-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_add_nutrition_minerals'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'stock_count'], name='idx_products_available'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'price'], name='idx_products_in_stock'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['order_count'], name='idx_products_popularity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-id'], name='idx_products_newest'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_percent'], name='idx_products_discount'),
        ),
    ]
