# Generated by Django 4.2.8 on 2026-01-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_add_product_breed_recommendation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(blank=True, help_text='Конкретная вариация (вес, вкус, размер)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productsku', verbose_name='Вариация товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productsku', verbose_name='Вариация товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku_name',
            field=models.CharField(blank=True, help_text='Например: "2 кг", "Курица", "M"', max_length=100, null=True, verbose_name='Название вариации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='animal',
            field=models.CharField(choices=[('dog', 'Для собак'), ('cat', 'Для кошек')], db_index=True, default='dog', help_text='DEPRECATED: Используйте animal_type', max_length=10, verbose_name='Животное (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Корм'), ('treats', 'Лакомства'), ('supplements', 'Добавки и витамины'), ('pharmacy', 'Ветаптека'), ('ammunition', 'Амуниция'), ('care', 'Средства по уходу'), ('transport', 'Транспортировка'), ('toys', 'Игрушки')], db_index=True, default='food', help_text='DEPRECATED: Используйте new_category', max_length=20, verbose_name='Категория (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: Используйте new_category.name', max_length=100, null=True, verbose_name='Название категории (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('canned', 'Консервы'), ('pouch', 'Паучи'), ('pate', 'Паштет'), ('holistic', 'Холистик'), ('diet', 'Диетический'), ('hypoallergenic', 'Гипоаллергенный'), ('dental', 'Для зубов'), ('training', 'Для дрессировки'), ('functional', 'Функциональные'), ('natural', 'Натуральные'), ('vitamins', 'Витамины'), ('omega3', 'Омега-3'), ('calcium', 'Кальций'), ('joint', 'Для суставов'), ('senior', 'Для пожилых'), ('immune', 'Иммунитет'), ('skin', 'Кожа и шерсть'), ('digestion', 'Пищеварение'), ('antiparasite', 'Средства от паразитов'), ('leashes', 'Поводки'), ('collars', 'Ошейники'), ('harnesses', 'Шлейки'), ('muzzles', 'Намордники'), ('clickers', 'Кликеры'), ('retractable', 'Рулетки'), ('lights', 'Подсветки'), ('multiboxes', 'Мультибоксы'), ('enclosures', 'Клетки'), ('pads', 'Пелёнки'), ('general', 'Общее')], db_index=True, help_text='DEPRECATED: Используйте new_category', max_length=30, null=True, verbose_name='Подкатегория (DEPRECATED)'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product', 'sku'), name='unique_cart_product_sku'),
        ),
    ]
