from django.core.management.base import BaseCommand
import importlib

from apps.pets.models import Medication, PetMedication


class Command(BaseCommand):
    help = "Seed medications reference data (upsert)."

    def handle(self, *args, **options):
        module = importlib.import_module(
            'apps.pets.migrations.0016_create_medications_and_fk'
        )
        medications = list(module.MEDICATIONS)
        medications.extend(self._build_extra_medications())

        for item in medications:
            Medication.objects.update_or_create(code=item['code'], defaults=item)

        existing_codes = (
            PetMedication.objects.exclude(medication_code__isnull=True)
            .values_list('medication_code', flat=True)
            .distinct()
        )
        for code in existing_codes:
            if not Medication.objects.filter(code=code).exists():
                Medication.objects.create(
                    code=code,
                    name_trade=code,
                    name_active=code,
                    category='other',
                    form='other',
                    species='both',
                    indications='Не указано',
                    typical_frequency=[],
                    notes='Добавлено автоматически из существующих записей.',
                )

        self.stdout.write(self.style.SUCCESS(
            f"Seeded medications: {len(medications)} items."
        ))

    def _build_extra_medications(self):
        base_items = [
            {'code': 'acyclovir', 'name': 'Ацикловир', 'category': 'antibiotic', 'species': 'both', 'indications': 'Вирусные инфекции'},
            {'code': 'albendazole', 'name': 'Альбендазол', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'allopurinol', 'name': 'Аллопуринол', 'category': 'other', 'species': 'dog', 'indications': 'Лейшманиоз'},
            {'code': 'amiodarone', 'name': 'Амиодарон', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'apomorphine', 'name': 'Апоморфин', 'category': 'gastrointestinal', 'species': 'dog', 'indications': 'Индукция рвоты'},
            {'code': 'aspirin', 'name': 'Аспирин', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'atenolol_generic', 'name': 'Атенолол', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'bacitracin', 'name': 'Бацитрацин', 'category': 'dermatological', 'species': 'both', 'indications': 'Инфекции кожи'},
            {'code': 'baclofen', 'name': 'Баклофен', 'category': 'other', 'species': 'dog', 'indications': 'Мышечные спазмы'},
            {'code': 'benazepril', 'name': 'Беназеприл', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'bromhexine', 'name': 'Бромгексин', 'category': 'other', 'species': 'both', 'indications': 'Муколитик'},
            {'code': 'bromocriptine', 'name': 'Бромокриптин', 'category': 'hormonal', 'species': 'dog', 'indications': 'Гиперпролактинемия'},
            {'code': 'butylscopolamine', 'name': 'Бускопан', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Спазмы ЖКТ'},
            {'code': 'calcitriol', 'name': 'Кальцитриол', 'category': 'supplement', 'species': 'both', 'indications': 'Поддержка кальция'},
            {'code': 'canakinumab', 'name': 'Канакинумаб', 'category': 'immunosuppressant', 'species': 'cat', 'indications': 'Воспалительные синдромы'},
            {'code': 'capsaicin', 'name': 'Капсаицин', 'category': 'analgesic', 'species': 'both', 'indications': 'Местное обезболивание'},
            {'code': 'cefuroxime', 'name': 'Цефуроксим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefixime', 'name': 'Цефиксим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefotaxime', 'name': 'Цефотаксим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefepime', 'name': 'Цефепим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'ceftazidime', 'name': 'Цефтазидим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefotetan', 'name': 'Цефотетан', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'chlorpropamide', 'name': 'Хлорпропамид', 'category': 'hormonal', 'species': 'dog', 'indications': 'Диабет'},
            {'code': 'ciclosporin', 'name': 'Циклоспорин', 'category': 'immunosuppressant', 'species': 'both', 'indications': 'Иммуносупрессия'},
            {'code': 'clotrimazole_generic', 'name': 'Клотримазол', 'category': 'dermatological', 'species': 'both', 'indications': 'Грибковые инфекции'},
            {'code': 'cobalamin', 'name': 'Кобаламин', 'category': 'supplement', 'species': 'both', 'indications': 'Дефицит витамина B12'},
            {'code': 'codeine', 'name': 'Кодеин', 'category': 'analgesic', 'species': 'dog', 'indications': 'Кашель и боль'},
            {'code': 'colchicine', 'name': 'Колхицин', 'category': 'other', 'species': 'dog', 'indications': 'Аутоиммунные воспаления'},
            {'code': 'corticotropin', 'name': 'Кортикотропин', 'category': 'hormonal', 'species': 'both', 'indications': 'Гормональная терапия'},
            {'code': 'dantrolene', 'name': 'Дантролен', 'category': 'other', 'species': 'dog', 'indications': 'Мышечные спазмы'},
            {'code': 'dapsone', 'name': 'Дапсон', 'category': 'immunosuppressant', 'species': 'dog', 'indications': 'Иммунные дерматозы'},
            {'code': 'demeclocycline', 'name': 'Демеклоциклин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'diazoxide', 'name': 'Диазоксид', 'category': 'hormonal', 'species': 'dog', 'indications': 'Гипогликемия'},
            {'code': 'dipyridamole', 'name': 'Дипиридамол', 'category': 'cardiac', 'species': 'dog', 'indications': 'Кардиология'},
            {'code': 'doxepin', 'name': 'Доксепин', 'category': 'antihistamine', 'species': 'both', 'indications': 'Аллергии и зуд'},
            {'code': 'doxylamine', 'name': 'Доксиламин', 'category': 'antihistamine', 'species': 'both', 'indications': 'Аллергии'},
            {'code': 'dronedarone', 'name': 'Дронедарон', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'epinephrine', 'name': 'Адреналин', 'category': 'other', 'species': 'both', 'indications': 'Шоковые состояния'},
            {'code': 'erythromycin', 'name': 'Эритромицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'esomeprazole', 'name': 'Эзомепразол', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Язвенная болезнь'},
            {'code': 'fentanyl', 'name': 'Фентанил', 'category': 'analgesic', 'species': 'both', 'indications': 'Сильная боль'},
            {'code': 'flumethasone', 'name': 'Флуметазон', 'category': 'hormonal', 'species': 'both', 'indications': 'Воспаление кожи'},
            {'code': 'flunixin', 'name': 'Флуниксин', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'fluconazole', 'name': 'Флуконазол', 'category': 'dermatological', 'species': 'both', 'indications': 'Грибковые инфекции'},
            {'code': 'fluticasone', 'name': 'Флутиказон', 'category': 'hormonal', 'species': 'both', 'indications': 'Воспаление'},
            {'code': 'fosfomycin', 'name': 'Фосфомицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Инфекции мочевыводящих путей'},
            {'code': 'furazolidone', 'name': 'Фуразолидон', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Инфекции ЖКТ'},
            {'code': 'gabapentin_generic', 'name': 'Габапентин', 'category': 'analgesic', 'species': 'both', 'indications': 'Нейропатическая боль'},
            {'code': 'gatifloxacin', 'name': 'Гатифлоксацин', 'category': 'ophthalmic', 'species': 'both', 'indications': 'Глазные инфекции'},
            {'code': 'glimepiride', 'name': 'Глимепирид', 'category': 'hormonal', 'species': 'dog', 'indications': 'Диабет'},
            {'code': 'griseofulvin', 'name': 'Гризеофульвин', 'category': 'dermatological', 'species': 'both', 'indications': 'Грибковые инфекции'},
            {'code': 'heparin', 'name': 'Гепарин', 'category': 'cardiac', 'species': 'both', 'indications': 'Антикоагулянт'},
            {'code': 'hyoscyamine', 'name': 'Гиосциамин', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Спазмы ЖКТ'},
            {'code': 'ibuprofen', 'name': 'Ибупрофен', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'indomethacin', 'name': 'Индометацин', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'ipratropium', 'name': 'Ипратропий', 'category': 'other', 'species': 'both', 'indications': 'Бронхоспазм'},
            {'code': 'itraconazole_generic', 'name': 'Итраконазол', 'category': 'dermatological', 'species': 'both', 'indications': 'Грибковые инфекции'},
            {'code': 'ketorolac', 'name': 'Кеторолак', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'lansoprazole', 'name': 'Лансопразол', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Язвенная болезнь'},
            {'code': 'levofloxacin', 'name': 'Левофлоксацин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'levoleucovorin', 'name': 'Леволейковорин', 'category': 'supplement', 'species': 'both', 'indications': 'Поддержка при терапии'},
            {'code': 'levamisole', 'name': 'Левамизол', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'lisinopril', 'name': 'Лизиноприл', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'lorazepam', 'name': 'Лоразепам', 'category': 'other', 'species': 'both', 'indications': 'Седация'},
            {'code': 'losartan', 'name': 'Лозартан', 'category': 'cardiac', 'species': 'both', 'indications': 'Гипертензия'},
            {'code': 'mebendazole', 'name': 'Мебендазол', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'meclizine', 'name': 'Меклизин', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Укачивание'},
            {'code': 'mefenamic', 'name': 'Мефенамовая кислота', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'megestrol', 'name': 'Мегестрол', 'category': 'hormonal', 'species': 'cat', 'indications': 'Контроль течки'},
            {'code': 'mesalamine', 'name': 'Месалазин', 'category': 'gastrointestinal', 'species': 'dog', 'indications': 'Воспаление кишечника'},
            {'code': 'metformin', 'name': 'Метформин', 'category': 'hormonal', 'species': 'dog', 'indications': 'Диабет'},
            {'code': 'morphine', 'name': 'Морфин', 'category': 'analgesic', 'species': 'both', 'indications': 'Сильная боль'},
            {'code': 'naloxone', 'name': 'Налоксон', 'category': 'other', 'species': 'both', 'indications': 'Антагонист опиоидов'},
            {'code': 'naproxen', 'name': 'Напроксен', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'nifedipine', 'name': 'Нифедипин', 'category': 'cardiac', 'species': 'cat', 'indications': 'Гипертензия'},
            {'code': 'nitrofurantoin', 'name': 'Нитрофурантоин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Инфекции мочевыводящих путей'},
            {'code': 'norfloxacin', 'name': 'Норфлоксацин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'ondansetron', 'name': 'Ондансетрон', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Рвота'},
            {'code': 'oseltamivir', 'name': 'Осельтамивир', 'category': 'antibiotic', 'species': 'both', 'indications': 'Вирусные инфекции'},
            {'code': 'pantoprazole', 'name': 'Пантопразол', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Язвенная болезнь'},
            {'code': 'paracetamol', 'name': 'Парацетамол', 'category': 'analgesic', 'species': 'dog', 'indications': 'Боль и температура'},
            {'code': 'pentoxifylline', 'name': 'Пентоксифиллин', 'category': 'cardiac', 'species': 'dog', 'indications': 'Сосудистые нарушения'},
            {'code': 'phenylbutazone', 'name': 'Фенилбутазон', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'phenytoin', 'name': 'Фенитоин', 'category': 'other', 'species': 'dog', 'indications': 'Судороги'},
            {'code': 'piperazine', 'name': 'Пиперазин', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Нематодозы'},
            {'code': 'piracetam', 'name': 'Пирацетам', 'category': 'other', 'species': 'dog', 'indications': 'Нейропротекция'},
            {'code': 'praziquantel_generic', 'name': 'Празиквантел', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Цестодозы'},
            {'code': 'propranolol', 'name': 'Пропранолол', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'pyridoxine', 'name': 'Пиридоксин', 'category': 'supplement', 'species': 'both', 'indications': 'Витамин B6'},
            {'code': 'ranolazine', 'name': 'Ранолазин', 'category': 'cardiac', 'species': 'both', 'indications': 'Кардиология'},
            {'code': 'rifaximin', 'name': 'Рифаксимин', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Диарея'},
            {'code': 'saccharomyces', 'name': 'Сахаромицеты', 'category': 'supplement', 'species': 'both', 'indications': 'Пробиотик'},
            {'code': 'salbutamol', 'name': 'Сальбутамол', 'category': 'other', 'species': 'both', 'indications': 'Бронхоспазм'},
            {'code': 'sertraline', 'name': 'Сертралин', 'category': 'other', 'species': 'both', 'indications': 'Тревожность'},
            {'code': 'sulfasalazine', 'name': 'Сульфасалазин', 'category': 'gastrointestinal', 'species': 'dog', 'indications': 'Колит'},
            {'code': 'tacrolimus', 'name': 'Такролимус', 'category': 'immunosuppressant', 'species': 'both', 'indications': 'Иммуносупрессия'},
            {'code': 'telmisartan', 'name': 'Телмисартан', 'category': 'cardiac', 'species': 'cat', 'indications': 'Гипертензия'},
            {'code': 'tetracycline', 'name': 'Тетрациклин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'thiabendazole', 'name': 'Тиабендазол', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'ticlopidine', 'name': 'Тиклопидин', 'category': 'cardiac', 'species': 'dog', 'indications': 'Антиагрегант'},
            {'code': 'tinidazole', 'name': 'Тинидазол', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Диарея'},
            {'code': 'tizanidine', 'name': 'Тизанидин', 'category': 'other', 'species': 'dog', 'indications': 'Мышечные спазмы'},
            {'code': 'toltrazuril', 'name': 'Толтразурил', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Кокцидиоз'},
            {'code': 'triamcinolone', 'name': 'Триамцинолон', 'category': 'hormonal', 'species': 'both', 'indications': 'Воспаление'},
            {'code': 'trimetazidine', 'name': 'Триметазидин', 'category': 'cardiac', 'species': 'dog', 'indications': 'Кардиология'},
            {'code': 'valacyclovir', 'name': 'Валацикловир', 'category': 'antibiotic', 'species': 'both', 'indications': 'Вирусные инфекции'},
            {'code': 'valsartan', 'name': 'Валсартан', 'category': 'cardiac', 'species': 'both', 'indications': 'Гипертензия'},
            {'code': 'vancomycin', 'name': 'Ванкомицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые инфекции'},
            {'code': 'verapamil', 'name': 'Верапамил', 'category': 'cardiac', 'species': 'cat', 'indications': 'Аритмии'},
            {'code': 'vitamin_a', 'name': 'Витамин A', 'category': 'supplement', 'species': 'both', 'indications': 'Поддержка зрения'},
            {'code': 'vitamin_k', 'name': 'Витамин K', 'category': 'supplement', 'species': 'both', 'indications': 'Свертываемость крови'},
            {'code': 'voriconazole', 'name': 'Вориконазол', 'category': 'dermatological', 'species': 'both', 'indications': 'Грибковые инфекции'},
            {'code': 'xylazine', 'name': 'Ксилазин', 'category': 'other', 'species': 'both', 'indications': 'Седация'},
            {'code': 'yohimbine', 'name': 'Йохимбин', 'category': 'other', 'species': 'both', 'indications': 'Антагонист седативных'},
            {'code': 'zidovudine', 'name': 'Зидовудин', 'category': 'antibiotic', 'species': 'cat', 'indications': 'Вирусные инфекции'},
            {'code': 'ampicillin_sulbactam', 'name': 'Ампициллин + сульбактам', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'piperacillin_tazobactam', 'name': 'Пиперациллин + тазобактам', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые бактериальные инфекции'},
            {'code': 'ticarcillin', 'name': 'Тикарциллин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'meropenem', 'name': 'Меропенем', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые бактериальные инфекции'},
            {'code': 'imipenem', 'name': 'Имипенем', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые бактериальные инфекции'},
            {'code': 'ertapenem', 'name': 'Эртапенем', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые бактериальные инфекции'},
            {'code': 'ceftazidime', 'name': 'Цефтазидим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefoperazone', 'name': 'Цефоперазон', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefotetan', 'name': 'Цефотетан', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'ceftaroline', 'name': 'Цефтаролин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefdinir', 'name': 'Цефдинир', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'ceftibuten', 'name': 'Цефтибутен', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefditoren', 'name': 'Цефдиторен', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefixime_generic', 'name': 'Цефиксим', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'minocycline', 'name': 'Миноциклин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'tigecycline', 'name': 'Тигециклин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'fusidic_acid', 'name': 'Фузидиевая кислота', 'category': 'antibiotic', 'species': 'both', 'indications': 'Инфекции кожи'},
            {'code': 'florfenicol', 'name': 'Флорфеникол', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'spectinomycin', 'name': 'Спектиномицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'spiramycin', 'name': 'Спирамицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cloxacillin', 'name': 'Клоксациллин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'oxytetracycline', 'name': 'Окситетрациклин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'roxithromycin', 'name': 'Рокситромицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'josamycin', 'name': 'Джозамицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'azlocillin', 'name': 'Азлоциллин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'carbenicillin', 'name': 'Карбенициллин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'colistin', 'name': 'Колистин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые инфекции'},
            {'code': 'polymyxin_e', 'name': 'Полимиксин E', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые инфекции'},
            {'code': 'daptomycin', 'name': 'Даптомицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Тяжелые инфекции'},
            {'code': 'rifabutin', 'name': 'Рифабутин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Инфекции'},
            {'code': 'cephapirin', 'name': 'Цефапирин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefotiam', 'name': 'Цефотиам', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefpirome', 'name': 'Цефпиром', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cefuroxime_axetil', 'name': 'Цефуроксим аксетил', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'cephalothin', 'name': 'Цефалотин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'lincomycin', 'name': 'Линкомицин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'tylosin_tartrate', 'name': 'Тилозина тартрат', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'tilmicosin', 'name': 'Тилмикозин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'tiamulin', 'name': 'Тиамулин', 'category': 'antibiotic', 'species': 'both', 'indications': 'Бактериальные инфекции'},
            {'code': 'fluralaner', 'name': 'Флураланер', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Блохи и клещи'},
            {'code': 'afoxolaner', 'name': 'Афоксоланер', 'category': 'antiparasitic', 'species': 'dog', 'indications': 'Блохи и клещи'},
            {'code': 'sarolaner', 'name': 'Сароланер', 'category': 'antiparasitic', 'species': 'dog', 'indications': 'Блохи и клещи'},
            {'code': 'lotilaner', 'name': 'Лотиланер', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Блохи и клещи'},
            {'code': 'milbemycin_oxime', 'name': 'Мильбемицин оксим', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'febantel', 'name': 'Фебантел', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'oxibendazole', 'name': 'Оксибендазол', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'doramectin', 'name': 'Дорамектин', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Паразиты'},
            {'code': 'eprinomectin', 'name': 'Эприномектин', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Паразиты'},
            {'code': 'emodepside', 'name': 'Эмодепсид', 'category': 'antiparasitic', 'species': 'cat', 'indications': 'Гельминтозы'},
            {'code': 'imidacloprid', 'name': 'Имидаклоприд', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Блохи'},
            {'code': 'permethrin', 'name': 'Перметрин', 'category': 'antiparasitic', 'species': 'dog', 'indications': 'Блохи и клещи'},
            {'code': 'methoprene', 'name': 'Метопрен', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Контроль блох'},
            {'code': 'diethylcarbamazine', 'name': 'Диэтилкарбамазин', 'category': 'antiparasitic', 'species': 'dog', 'indications': 'Профилактика дирофиляриоза'},
            {'code': 'spinosad', 'name': 'Спиносад', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Блохи'},
            {'code': 'spinetoram', 'name': 'Спинеторам', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Блохи'},
            {'code': 'pyrantel_pamoate', 'name': 'Пирантел памоат', 'category': 'antiparasitic', 'species': 'both', 'indications': 'Гельминтозы'},
            {'code': 'diclofenac', 'name': 'Диклофенак', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'celecoxib', 'name': 'Целекоксиб', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'etodolac', 'name': 'Этодолак', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'piroxicam', 'name': 'Пироксикам', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'meclofenamate', 'name': 'Меклофенамат', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'tolmetin', 'name': 'Толметин', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'metamizole', 'name': 'Метамизол', 'category': 'analgesic', 'species': 'both', 'indications': 'Болевой синдром'},
            {'code': 'hydromorphone', 'name': 'Гидроморфон', 'category': 'analgesic', 'species': 'both', 'indications': 'Сильная боль'},
            {'code': 'oxycodone', 'name': 'Оксикодон', 'category': 'analgesic', 'species': 'both', 'indications': 'Сильная боль'},
            {'code': 'meperidine', 'name': 'Меперидин', 'category': 'analgesic', 'species': 'both', 'indications': 'Болевой синдром'},
            {'code': 'nalbuphine', 'name': 'Налбуфин', 'category': 'analgesic', 'species': 'both', 'indications': 'Болевой синдром'},
            {'code': 'tapentadol', 'name': 'Тапентадол', 'category': 'analgesic', 'species': 'both', 'indications': 'Болевой синдром'},
            {'code': 'dexketoprofen', 'name': 'Декскетопрофен', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'nabumetone', 'name': 'Набуметон', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'indoprofen', 'name': 'Индопрофен', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'flurbiprofen_systemic', 'name': 'Флурбипрофен', 'category': 'nsaid', 'species': 'dog', 'indications': 'Боль и воспаление'},
            {'code': 'torasemide', 'name': 'Торасемид', 'category': 'cardiac', 'species': 'both', 'indications': 'Отёки'},
            {'code': 'hydrochlorothiazide', 'name': 'Гидрохлоротиазид', 'category': 'cardiac', 'species': 'both', 'indications': 'Отёки'},
            {'code': 'ramipril', 'name': 'Рамиприл', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'quinapril', 'name': 'Квинаприл', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'sotalol', 'name': 'Соталол', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'carvedilol', 'name': 'Карведилол', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'isosorbide_dinitrate', 'name': 'Изосорбида динитрат', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечные заболевания'},
            {'code': 'nitroglycerin', 'name': 'Нитроглицерин', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечные заболевания'},
            {'code': 'clopidogrel', 'name': 'Клопидогрел', 'category': 'cardiac', 'species': 'both', 'indications': 'Профилактика тромбов'},
            {'code': 'warfarin', 'name': 'Варфарин', 'category': 'cardiac', 'species': 'both', 'indications': 'Антикоагулянт'},
            {'code': 'dobutamine', 'name': 'Добутамин', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'dopamine', 'name': 'Допамин', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'procainamide', 'name': 'Прокаинамид', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'mexiletine', 'name': 'Мексилетин', 'category': 'cardiac', 'species': 'both', 'indications': 'Аритмии'},
            {'code': 'milrinone', 'name': 'Милринон', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечная недостаточность'},
            {'code': 'ivabradine', 'name': 'Ивабрадин', 'category': 'cardiac', 'species': 'both', 'indications': 'Сердечные заболевания'},
            {'code': 'hydralazine', 'name': 'Гидралазин', 'category': 'cardiac', 'species': 'both', 'indications': 'Гипертензия'},
            {'code': 'misoprostol', 'name': 'Мизопростол', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Язвенная болезнь'},
            {'code': 'bismuth_subsalicylate', 'name': 'Салицилат висмута', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Диарея'},
            {'code': 'psyllium', 'name': 'Псиллиум', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Регуляция стула'},
            {'code': 'cisapride', 'name': 'Цизаприд', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Гастропарез'},
            {'code': 'domperidone', 'name': 'Домперидон', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Тошнота и рвота'},
            {'code': 'bismuth_subcitrate', 'name': 'Субцитрат висмута', 'category': 'gastrointestinal', 'species': 'both', 'indications': 'Язвенная болезнь'},
        ]

        extras = []
        seen_codes = set()
        for item in base_items:
            if item['code'] in seen_codes:
                continue
            seen_codes.add(item['code'])
            extras.append({
                'code': item['code'],
                'name_trade': item['name'],
                'name_active': item['name'],
                'category': item['category'],
                'form': 'tablets',
                'species': item['species'],
                'indications': item['indications'],
                'typical_frequency': ['once_daily'],
            })
        return extras
