# Generated by Django 4.2.8 on 2025-12-20 11:29

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_pet_allergies_pet_favorite_foods_pet_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, help_text='Порода (опционально)', max_length=100, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Когда был создан профиль питомца', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения для расчёта возраста и календаря', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор питомца', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(help_text='Кличка питомца', max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(help_text='Владелец питомца', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('fish', 'Рыбка'), ('reptile', 'Рептилия'), ('other', 'Другое')], help_text='Вид животного (собака, кошка, птица и т.д.)', max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Временная метка последнего изменения', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес в кг для рекомендаций по питанию', max_digits=5, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', '-created_at'], name='pets_owner_i_56be6d_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='pets_species_a3549a_idx'),
        ),
    ]
