# Generated by Django 4.2.8 on 2025-12-24 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0004_add_health_issues_and_activity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('feeding', 'Кормление'), ('medication', 'Лекарства'), ('vaccination', 'Вакцинация'), ('vet_visit', 'Посещение ветеринара'), ('grooming', 'Уход за шерстью'), ('walk', 'Прогулка'), ('training', 'Тренировка'), ('hygiene', 'Гигиена'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('biweekly', 'Раз в две недели'), ('monthly', 'Ежемесячно'), ('quarterly', 'Раз в квартал'), ('yearly', 'Ежегодно')], default='once', max_length=20, verbose_name='Частота повторения')),
                ('reminder_date', models.DateField(verbose_name='Дата напоминания')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Время напоминания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Уведомлять по email')),
                ('notify_push', models.BooleanField(default=True, verbose_name='Push-уведомление')),
                ('notify_before', models.PositiveIntegerField(default=60, verbose_name='Напоминать за (минут)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'db_table': 'reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
