# Generated by Django 5.1.5 on 2026-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_add_supplement_rule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='macrotargetrule',
            new_name='macro_targe_scope_f8c8d8_idx',
            old_name='macro_targe_scope_8a2b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='macrotargetrule',
            new_name='macro_targe_priorit_559a8c_idx',
            old_name='macro_targe_priorit_d3e4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritioncaprule',
            new_name='nutrition_c_scope_590fa3_idx',
            old_name='nutrition_c_scope_258d0c_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritionfactorrule',
            new_name='nutrition_f_scope_45dd3e_idx',
            old_name='nutrition_f_scope_641f6b_idx',
        ),
        migrations.RenameIndex(
            model_name='supplementrule',
            new_name='supplement__scope_73b345_idx',
            old_name='supplement__scope_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='supplementrule',
            new_name='supplement__priorit_8433de_idx',
            old_name='supplement__priorit_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='supplementrule',
            new_name='supplement__supplem_579841_idx',
            old_name='supplement__supplem_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='macrotargetrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutritioncaprule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nutritionfactorrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplementrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
