# Generated by Django 5.1.5 on 2026-06-24 20:45

import core.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_rename_macro_targe_scope_8a2b1c_idx_macro_targe_scope_f8c8d8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Название рецепта')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Бренд')),
                ('line', models.CharField(blank=True, max_length=255, verbose_name='Линейка')),
                ('recipe_key', models.CharField(blank=True, db_index=True, help_text='Нормализованный бренд+линейка+вкус+форма для слияния дублей вручную', max_length=255, verbose_name='Ключ дедупликации')),
                ('species', models.CharField(blank=True, choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('other', 'Другое')], max_length=10, verbose_name='Вид животного')),
                ('food_form', models.CharField(blank=True, choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('treat', 'Лакомство'), ('other', 'Другое')], max_length=10, verbose_name='Форма корма')),
                ('life_stage', models.CharField(blank=True, help_text='puppy/kitten/adult/senior/all', max_length=20, verbose_name='Возрастная группа')),
                ('size_group', models.CharField(blank=True, max_length=20, verbose_name='Размер породы')),
                ('diet_purpose', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None, verbose_name='Назначение (ЖКТ/почки/мочевая/кожа/вес...)')),
                ('is_sterilized', models.BooleanField(blank=True, null=True, verbose_name='Для стерилизованных')),
                ('is_sensitive_digestion', models.BooleanField(blank=True, null=True, verbose_name='Чувствительное пищеварение')),
                ('is_urinary', models.BooleanField(blank=True, null=True, verbose_name='Мочевыводящая/МКБ')),
                ('is_weight_control', models.BooleanField(blank=True, null=True, verbose_name='Контроль веса')),
                ('is_grain_free', models.BooleanField(blank=True, null=True, verbose_name='Беззерновой')),
                ('is_hypoallergenic', models.BooleanField(blank=True, null=True, verbose_name='Гипоаллергенный')),
                ('kcal_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ккал/100 г')),
                ('protein_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белок, %')),
                ('fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жир, %')),
                ('fiber_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Клетчатка, %')),
                ('ash_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Зола, %')),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Влажность, %')),
                ('calcium_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кальций, %')),
                ('phosphorus_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фосфор, %')),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None, verbose_name='Состав (ингредиенты по порядку)')),
                ('main_protein', models.CharField(blank=True, max_length=80, verbose_name='Основной белок')),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None, verbose_name='Аллергены')),
                ('source', models.CharField(blank=True, db_index=True, help_text='dinozavrik / manual / ...', max_length=30, verbose_name='Источник данных')),
                ('parse_status', models.CharField(choices=[('pending', 'Не обрабатывался'), ('auto_parsed', 'Распознано автоматически'), ('partial', 'Распознано частично'), ('failed', 'Не распознано')], db_index=True, default='pending', max_length=20, verbose_name='Статус парсинга')),
                ('review_status', models.CharField(choices=[('unverified', 'Не проверено'), ('auto_parsed', 'Авто-распознано'), ('manual_verified', 'Проверено вручную')], db_index=True, default='unverified', max_length=20, verbose_name='Статус проверки')),
                ('field_confidence', models.JSONField(blank=True, default=dict, help_text='{поле: supplier|parsed|estimated|manual|unknown}', verbose_name='Уверенность по полям')),
                ('is_recommendable', models.BooleanField(db_index=True, default=False, verbose_name='Разрешён в подбор')),
                ('recommend_block_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None, verbose_name='Почему не в подборе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рецепт корма',
                'verbose_name_plural': 'База питания (рецепты)',
                'db_table': 'food_recipes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['species', 'food_form'], name='idx_recipe_species_form'), models.Index(fields=['is_recommendable', 'review_status'], name='idx_recipe_gate')],
            },
        ),
        migrations.CreateModel(
            name='SupplierRawItem',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=30, verbose_name='Источник')),
                ('external_id', models.CharField(db_index=True, max_length=120, verbose_name='Внешний ID (xmlId)')),
                ('article_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Артикул (CODE_1C/CML2_ARTICLE)')),
                ('raw_json', models.JSONField(default=dict, verbose_name='Сырые данные')),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('food_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_items', to='pets.foodrecipe')),
            ],
            options={
                'verbose_name': 'Сырьё поставщика',
                'verbose_name_plural': 'Сырьё поставщиков',
                'db_table': 'supplier_raw_items',
                'ordering': ['-imported_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
