# Generated by Django 5.1.5 on 2026-06-24 21:10

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_foodrecipe_supplierrawitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='agency_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Агентский %% (предст.)'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='nutrition_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Полные ккал+БЖУ (точная норма)'),
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, max_length=30, verbose_name='Источник')),
                ('article_number', models.CharField(db_index=True, max_length=120, verbose_name='Артикул (CODE_1C, ключ sync)')),
                ('package_name', models.CharField(blank=True, max_length=120, verbose_name='Фасовка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('agency_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Агентский %%')),
                ('barcode', models.CharField(blank=True, max_length=60, verbose_name='Штрихкод')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырьё оффера')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pets.foodrecipe')),
            ],
            options={
                'verbose_name': 'Оффер поставщика (фасовка)',
                'verbose_name_plural': 'Офферы поставщиков',
                'db_table': 'supplier_offers',
                'ordering': ['package_name'],
                'unique_together': {('source', 'article_number')},
            },
        ),
    ]
