# Generated by Django 5.1.5 on 2026-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_foodrecipe_agency_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieroffer',
            name='package_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Вес фасовки, кг'),
        ),
    ]
