# Generated by Django 5.1.5 on 2026-06-25 06:20

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_supplieroffer_package_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBrandRule',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Бренд')),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило приоритета бренда',
                'verbose_name_plural': 'Бизнес-правила брендов',
                'db_table': 'food_brand_rules',
                'ordering': ['-priority', 'brand'],
            },
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='business_priority',
            field=models.IntegerField(db_index=True, default=0, help_text='-100..100. Поднимает рецепт среди ПОДХОДЯЩИХ. Не перебивает медицину/аллергии.', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Бизнес-приоритет'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='customer_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг покупателей'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='expert_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Экспертная оценка'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='is_promoted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Продвигаемый'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='transition_message',
            field=models.CharField(blank=True, help_text='Ручной безопасный текст. Без медицинских обещаний.', max_length=300, verbose_name='Сообщение пересадки'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='transition_target_reason',
            field=models.CharField(blank=True, max_length=120, verbose_name='Причина пересадки'),
        ),
    ]
