# Generated by Django 5.1.5 on 2026-06-25 18:23

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0025_foodbrandrule_foodrecipe_business_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('supplier_type', models.CharField(choices=[('feed', 'Фид'), ('api', 'API'), ('manual', 'Вручную')], default='feed', max_length=20, verbose_name='Тип')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('payment_model', models.CharField(choices=[('partner_checkout', 'Оплата у партнёра'), ('platform_checkout', 'Оплата на платформе'), ('cash_on_pickup', 'Оплата при получении')], default='partner_checkout', max_length=30, verbose_name='Модель оплаты')),
                ('settlement_model', models.CharField(choices=[('agent_commission', 'Агентская комиссия'), ('resale_margin', 'Перепродажная маржа'), ('manual_reconciliation', 'Ручная сверка')], default='agent_commission', max_length=30, verbose_name='Модель расчётов')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='source',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Источник (legacy/backup)'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='pets.supplier', verbose_name='Поставщик'),
        ),
    ]
