# Generated by Django 5.1.5 on 2026-06-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0027_seed_dinozavrik_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplieroffer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.UniqueConstraint(fields=('supplier', 'article_number'), name='uniq_offer_supplier_article'),
        ),
    ]
