# Generated by Django 5.1.5 on 2026-06-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0028_alter_supplieroffer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierrawitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supplierrawitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_items', to='pets.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierrawitem',
            name='source',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Источник (legacy/backup)'),
        ),
        migrations.AddConstraint(
            model_name='supplierrawitem',
            constraint=models.UniqueConstraint(fields=('supplier', 'external_id'), name='uniq_raw_supplier_external'),
        ),
    ]
