# Generated by Django 5.1.5 on 2026-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0030_link_rawitems_to_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_mixed_breed',
            field=models.BooleanField(default=False, verbose_name='Метис / беспородный'),
        ),
    ]
