# Generated by Django 5.1.5 on 2026-06-30 08:49

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0031_pet_is_mixed_breed'),
        ('shop', '0030_product_supplier_productsku_supplier_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalogSyncLog',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, default='dinozavrik_json', max_length=80, verbose_name='Источник')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('started_at', models.DateTimeField(verbose_name='Начало импорта')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание импорта')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=20, verbose_name='Статус')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего позиций')),
                ('created_items', models.IntegerField(default=0, verbose_name='Создано')),
                ('updated_items', models.IntegerField(default=0, verbose_name='Обновлено')),
                ('unchanged_items', models.IntegerField(default=0, verbose_name='Без изменений')),
                ('failed_items', models.IntegerField(default=0, verbose_name='Ошибки')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='pets.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Журнал синхронизации поставщика',
                'verbose_name_plural': 'Журналы синхронизации поставщиков',
                'db_table': 'supplier_catalog_sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['supplier', '-started_at'], name='idx_supplier_sync_started'), models.Index(fields=['source', 'status'], name='idx_sync_source_status')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductSubmission',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('needs_fix', 'Нужны исправления'), ('submitted', 'Отправлено на проверку'), ('approved_for_shop', 'Разрешено для магазина'), ('approved_for_recommendation', 'Разрешено для подбора'), ('rejected', 'Отклонено'), ('archived', 'Архив')], db_index=True, default='draft', max_length=40, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('supplier_comment', models.TextField(blank=True, verbose_name='Комментарий поставщика')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные черновика')),
                ('validation_errors', models.JSONField(blank=True, default=dict, verbose_name='Ошибки валидации')),
                ('changed_fields', models.JSONField(blank=True, default=dict, verbose_name='Изменённые поля')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('food_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_submissions', to='pets.foodrecipe', verbose_name='Утверждённый рецепт')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_submissions', to='shop.product', verbose_name='Товар витрины')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_products', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('source_raw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_submissions', to='pets.supplierrawitem', verbose_name='Исходная запись фида')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_supplier_products', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_submissions', to='pets.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заявка поставщика на корм',
                'verbose_name_plural': 'Заявки поставщиков на корма',
                'db_table': 'supplier_product_submissions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['supplier', 'status'], name='idx_supplier_submission_status'), models.Index(fields=['status', '-updated_at'], name='idx_submission_review_queue')],
            },
        ),
        migrations.CreateModel(
            name='SupplierUserAccess',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('editor', 'Редактор'), ('analyst', 'Аналитик')], default='manager', max_length=20, verbose_name='Роль в кабинете')),
                ('can_edit_catalog', models.BooleanField(default=True, verbose_name='Может редактировать ассортимент')),
                ('can_view_finance', models.BooleanField(default=True, verbose_name='Может видеть финансы')),
                ('can_export_reports', models.BooleanField(default=True, verbose_name='Может экспортировать отчёты')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='pets.supplier', verbose_name='Поставщик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя поставщика',
                'verbose_name_plural': 'Доступы пользователей поставщиков',
                'db_table': 'supplier_user_accesses',
                'indexes': [models.Index(fields=['supplier', 'is_active'], name='idx_supplier_access_supplier'), models.Index(fields=['user', 'is_active'], name='idx_supplier_access_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'supplier'), name='uniq_supplier_user_access')],
            },
        ),
    ]
