# Generated by Django 4.2.8 on 2025-12-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_usercourse_unique_together_usercourse_pet_and_more'),
        ('pets', '0003_alter_pet_breed_alter_pet_created_at_and_more'),
        ('shop', '0006_add_discount_percent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='Подтверждение согласия с условиями использования для курсов', verbose_name='Согласие с условиями'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Питомец, для которого приобретается курс (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('cart', 'course', 'pet'), name='unique_cart_course_pet'),
        ),
    ]
