# Generated by Django 4.2.8 on 2025-12-24 17:17

import core.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_fix_cartitem_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.CharField(default=core.utils.generate_uuid7, editable=False, help_text='UUIDv7 идентификатор возврата', max_length=36, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество для возврата')),
                ('reason', models.CharField(choices=[('defective', 'Брак/Повреждение'), ('wrong_item', 'Не тот товар'), ('not_satisfied', 'Не подошел'), ('changed_mind', 'Передумал'), ('other', 'Другое')], max_length=20, verbose_name='Причина возврата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('requested', 'Запрошено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('received', 'Получено'), ('refunded', 'Возвращены средства')], default='requested', max_length=20, verbose_name='Статус')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата средств')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.orderitem', verbose_name='Элемент заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'db_table': 'returns',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='returns_user_id_b9ddd5_idx'), models.Index(fields=['order', 'status'], name='returns_order_i_34dbe0_idx'), models.Index(fields=['status'], name='returns_status_72f13e_idx')],
            },
        ),
    ]
