# Generated by Django 4.2.8 on 2026-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_add_kcal_per_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_calcium',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Содержание кальция в %', max_digits=5, null=True, verbose_name='Кальций (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_omega3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание омега-3 жирных кислот в %', max_digits=5, null=True, verbose_name='Омега-3 (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_omega6',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Содержание омега-6 жирных кислот в %', max_digits=5, null=True, verbose_name='Омега-6 (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_phosphorus',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Содержание фосфора в %', max_digits=5, null=True, verbose_name='Фосфор (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Корм'), ('treats', 'Лакомства'), ('supplements', 'Добавки и витамины'), ('pharmacy', 'Ветаптека'), ('ammunition', 'Амуниция'), ('care', 'Средства по уходу'), ('transport', 'Транспортировка'), ('toys', 'Игрушки')], db_index=True, default='food', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('dry', 'Сухой'), ('wet', 'Влажный'), ('canned', 'Консервы'), ('pouch', 'Паучи'), ('pate', 'Паштет'), ('holistic', 'Холистик'), ('diet', 'Диетический'), ('hypoallergenic', 'Гипоаллергенный'), ('dental', 'Для зубов'), ('training', 'Для дрессировки'), ('functional', 'Функциональные'), ('natural', 'Натуральные'), ('vitamins', 'Витамины'), ('omega3', 'Омега-3'), ('calcium', 'Кальций'), ('joint', 'Для суставов'), ('senior', 'Для пожилых'), ('immune', 'Иммунитет'), ('skin', 'Кожа и шерсть'), ('digestion', 'Пищеварение'), ('antiparasite', 'Средства от паразитов'), ('leashes', 'Поводки'), ('collars', 'Ошейники'), ('harnesses', 'Шлейки'), ('muzzles', 'Намордники'), ('clickers', 'Кликеры'), ('retractable', 'Рулетки'), ('lights', 'Подсветки'), ('multiboxes', 'Мультибоксы'), ('enclosures', 'Клетки'), ('pads', 'Пелёнки'), ('general', 'Общее')], db_index=True, max_length=30, null=True, verbose_name='Подкатегория'),
        ),
    ]
