# Generated by Django 4.2.8 on 2026-01-24 14:50

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID из API')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='Логотип')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='Сайт')),
                ('brand_class', models.CharField(blank=True, choices=[('economy', 'Эконом'), ('premium', 'Премиум'), ('super_premium', 'Супер-премиум'), ('holistic', 'Холистик')], help_text='economy/premium/super_premium/holistic', max_length=20, null=True, verbose_name='Класс бренда')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна производителя')),
                ('priority', models.SmallIntegerField(default=5, help_text='Приоритет для рекомендаций (1-10)', verbose_name='Приоритет')),
                ('product_count', models.IntegerField(default=0, verbose_name='Количество товаров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'shop_brands',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, help_text='ID категории из внешнего API', null=True, unique=True, verbose_name='ID из API')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('depth', models.SmallIntegerField(default=0, help_text='0=корневая, 1=подкатегория, 2=под-подкатегория', verbose_name='Глубина вложенности')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Полный путь ID для быстрого поиска [2133, 2137, 2322]', size=None, verbose_name='Путь в иерархии')),
                ('animal_type', models.CharField(choices=[('dog', 'Для собак'), ('cat', 'Для кошек'), ('all', 'Для всех')], db_index=True, default='all', max_length=10, verbose_name='Тип животного')),
                ('product_group', models.CharField(blank=True, choices=[('food', 'Корм'), ('treats', 'Лакомства'), ('vet', 'Ветаптека'), ('vitamins', 'Витамины и добавки'), ('clothes', 'Одежда'), ('equipment', 'Амуниция'), ('grooming', 'Груминг'), ('housing', 'Транспортировка и содержание'), ('toys', 'Игрушки'), ('bowls', 'Миски'), ('toilet', 'Туалеты и принадлежности'), ('other', 'Прочее')], help_text='Для логики бэкенда: food/treats/vet/vitamins/clothes/equipment/grooming/housing/toys/bowls/toilet/other', max_length=20, null=True, verbose_name='Группа товаров')),
                ('product_count', models.IntegerField(default=0, help_text='Денормализовано для быстрого отображения', verbose_name='Количество товаров')),
                ('icon', models.CharField(blank=True, help_text='Emoji или класс иконки', max_length=50, verbose_name='Иконка')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Изображение категории')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'shop_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, verbose_name='ID SKU из API')),
                ('sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, help_text='"2 кг", "Курица", "M"', max_length=255, verbose_name='Название вариации')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество на складе')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='0.4, 2.0, 10.0', max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('weight_display', models.CharField(blank=True, help_text='"400 г", "2 кг", "10 кг"', max_length=20, verbose_name='Вес (отображение)')),
                ('flavor', models.CharField(blank=True, help_text='chicken, beef, fish, lamb', max_length=50, null=True, verbose_name='Вкус (код)')),
                ('flavor_display', models.CharField(blank=True, help_text='"Курица", "Говядина", "Рыба"', max_length=100, verbose_name='Вкус (отображение)')),
                ('size_code', models.CharField(blank=True, help_text='XS, S, M, L, XL, XXL', max_length=10, null=True, verbose_name='Размер (код)')),
                ('size_back_cm', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина спины (см)')),
                ('size_chest_cm', models.SmallIntegerField(blank=True, null=True, verbose_name='Обхват груди (см)')),
                ('size_neck_cm', models.SmallIntegerField(blank=True, null=True, verbose_name='Обхват шеи (см)')),
                ('color', models.CharField(blank=True, help_text='red, blue, black', max_length=50, null=True, verbose_name='Цвет (код)')),
                ('color_display', models.CharField(blank=True, help_text='"Красный", "Синий"', max_length=100, verbose_name='Цвет (отображение)')),
                ('color_hex', models.CharField(blank=True, help_text='#FF0000', max_length=7, null=True, verbose_name='Цвет HEX')),
                ('volume_ml', models.IntegerField(blank=True, help_text='250, 500, 1000', null=True, verbose_name='Объём (мл)')),
                ('volume_display', models.CharField(blank=True, help_text='"250 мл", "1 л"', max_length=20, verbose_name='Объём (отображение)')),
                ('pack_quantity', models.IntegerField(blank=True, help_text='10, 50, 100 (пелёнок, таблеток)', null=True, verbose_name='Количество в упаковке')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные из API', verbose_name='Характеристики')),
                ('sort_order', models.SmallIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('is_default', models.BooleanField(default=False, help_text='Вариация, отображаемая по умолчанию', verbose_name='По умолчанию')),
                ('status', models.SmallIntegerField(default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'SKU товара',
                'verbose_name_plural': 'SKU товаров',
                'db_table': 'shop_product_skus',
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(blank=True, choices=[('puppy', 'Щенок'), ('kitten', 'Котёнок'), ('adult', 'Взрослый'), ('senior', 'Пожилой'), ('all', 'Все возрасты')], help_text='puppy/kitten/adult/senior/all', max_length=20, null=True, verbose_name='Возрастная группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Для собак'), ('cat', 'Для кошек'), ('all', 'Для всех')], db_index=True, default='dog', help_text='dog/cat/all', max_length=10, verbose_name='Тип животного'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_details',
            field=models.JSONField(blank=True, default=dict, help_text='ВСЕ специфичные данные категории (нутриенты, размеры, инструкции и т.д.)', verbose_name='Детали по категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Зачёркнутая цена для отображения скидки', max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='["urinary", "obesity", "joint", "skin", "digestive"]', size=None, verbose_name='Показания по здоровью'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL основного изображения (загружается сразу в каталоге)', max_length=500, null=True, verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Есть в наличии', verbose_name='В наличии (новое поле)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_grain_free',
            field=models.BooleanField(default=False, verbose_name='Беззерновой'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hypoallergenic',
            field=models.BooleanField(default=False, verbose_name='Гипоаллергенный'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_veterinary',
            field=models.BooleanField(default=False, verbose_name='Ветеринарная диета'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, choices=[('food', 'Корм'), ('treats', 'Лакомства'), ('vet', 'Ветаптека'), ('vitamins', 'Витамины и добавки'), ('clothes', 'Одежда'), ('equipment', 'Амуниция'), ('grooming', 'Груминг'), ('housing', 'Транспортировка и содержание'), ('toys', 'Игрушки'), ('bowls', 'Миски'), ('toilet', 'Туалеты и принадлежности'), ('other', 'Прочее')], db_index=True, help_text='food/treats/vet/vitamins/clothes/equipment/grooming/housing/toys/bowls/toilet/other', max_length=20, null=True, verbose_name='Группа товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Рейтинг 0-5', max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Превью для карточки каталога', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_group',
            field=models.CharField(blank=True, choices=[('mini', 'Миниатюрный'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный'), ('giant', 'Гигантский'), ('all', 'Все размеры')], help_text='mini/small/medium/large/giant/all', max_length=20, null=True, verbose_name='Размерная группа'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_count',
            field=models.SmallIntegerField(default=1, verbose_name='Количество вариаций'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL (из поля url API)', max_length=500, null=True, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(default=1, help_text='1=активен, 0=неактивен', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        # FK поля должны быть добавлены ДО индексов, которые их используют
        migrations.AddField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Родительская категория'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_class', '-priority'], name='shop_brands_brand_c_d056c8_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['external_id'], name='shop_brands_externa_cf5c7a_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_category',
            field=models.ForeignKey(blank=True, help_text='Связь с иерархией категорий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Категория (новая)'),
        ),
        # Теперь добавляем индексы, когда все поля существуют
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['animal_type', 'new_category', 'is_available', 'status', 'price'], name='idx_products_catalog_new'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['animal_type', 'product_group', 'is_available'], name='idx_products_group'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'status'], name='idx_products_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating', '-rating_count'], name='idx_products_rating'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['animal_type', 'is_grain_free', 'is_hypoallergenic', 'is_veterinary', 'age_group', 'size_group'], name='idx_products_food_filters'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='idx_products_slug'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product', 'status', 'available'], name='idx_skus_product'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['weight_kg'], name='idx_skus_weight'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['flavor'], name='idx_skus_flavor'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['size_code'], name='idx_skus_size'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['color'], name='idx_skus_color'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['external_id'], name='idx_skus_external'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('product', 'sku'), name='unique_product_sku'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='shop_catego_parent__56992e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['animal_type', 'product_group'], name='shop_catego_animal__db4cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['depth', 'is_active', 'sort_order'], name='shop_catego_depth_ae13e3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['external_id'], name='shop_catego_externa_b50582_idx'),
        ),
    ]
