# Generated by Django 4.2.8 on 2026-01-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_allergy_healthcondition_nutritioncoefficient_and_more'),
        ('shop', '0019_add_new_shop_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBreedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('size', 'По размеру'), ('health', 'По здоровью'), ('allergy', 'По аллергиям'), ('age', 'По возрасту'), ('manual', 'Ручная рекомендация'), ('auto', 'Авто (комплексный)')], default='auto', max_length=20, verbose_name='Тип соответствия')),
                ('suitability', models.CharField(choices=[('ideal', 'Идеально подходит'), ('recommended', 'Рекомендуется'), ('suitable', 'Подходит'), ('caution', 'С осторожностью'), ('not_recommended', 'Не рекомендуется')], default='suitable', max_length=20, verbose_name='Уровень совместимости')),
                ('score', models.SmallIntegerField(default=50, help_text='0-100, используется для сортировки рекомендаций', verbose_name='Оценка совместимости')),
                ('reason', models.CharField(blank=True, help_text='Например: "Подходит для крупных пород" или "Поддержка суставов"', max_length=255, verbose_name='Причина рекомендации')),
                ('is_auto', models.BooleanField(default=True, help_text='True = создана автоматически, False = добавлена вручную', verbose_name='Автоматическая')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='pets.breed', verbose_name='Порода')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_recommendations', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рекомендация товара для породы',
                'verbose_name_plural': 'Рекомендации товаров для пород',
                'db_table': 'shop_product_breed_recommendations',
                'ordering': ['-score', 'breed__name'],
                'indexes': [models.Index(fields=['product', 'suitability', '-score'], name='idx_breed_rec_product'), models.Index(fields=['breed', 'suitability', '-score'], name='idx_breed_rec_breed'), models.Index(fields=['match_type'], name='idx_breed_rec_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='productbreedrecommendation',
            constraint=models.UniqueConstraint(fields=('product', 'breed'), name='unique_product_breed'),
        ),
    ]
