# Generated by Django 4.2.8 on 2026-02-01 18:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0021_add_sku_to_cart_and_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_details', serialize=False, to='shop.product', verbose_name='Товар')),
                ('product_type', models.CharField(choices=[('food', 'Корм'), ('treat', 'Лакомство'), ('supplement', 'Витамины/добавки')], default='food', max_length=20, verbose_name='Тип продукта')),
                ('target_size', models.CharField(blank=True, choices=[('toy', 'Той'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный'), ('giant', 'Гигантский'), ('all', 'Все размеры')], max_length=10, null=True, verbose_name='Целевой размер')),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'Низкая'), ('normal', 'Нормальная'), ('high', 'Высокая')], max_length=10, null=True, verbose_name='Уровень активности')),
                ('grain_free', models.BooleanField(default=False, verbose_name='Беззерновой')),
                ('is_hypoallergenic', models.BooleanField(default=False, verbose_name='Гипоаллергенный')),
                ('is_veterinary', models.BooleanField(default=False, verbose_name='Ветеринарная диета')),
                ('special_diet', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='Специальные назначения')),
                ('compatibility_group', models.CharField(choices=[('regular', 'Обычный'), ('hypoallergenic', 'Гипоаллергенный'), ('therapeutic_renal', 'Лечебный: почки'), ('therapeutic_diabetic', 'Лечебный: диабет'), ('therapeutic_digestive', 'Лечебный: ЖКТ'), ('therapeutic_weight', 'Лечебный: вес'), ('therapeutic_urinary', 'Лечебный: МКБ')], default='regular', max_length=30, verbose_name='Группа совместимости')),
                ('kibble_size', models.CharField(blank=True, choices=[('small', 'Мелкая'), ('medium', 'Средняя'), ('large', 'Крупная')], max_length=10, null=True, verbose_name='Размер гранулы')),
                ('shelf_life_months', models.IntegerField(blank=True, null=True, verbose_name='Срок годности (мес)')),
                ('storage', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('meat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент мяса')),
                ('energy_kcal_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Калорийность (ккал/100г)')),
                ('protein_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Белок (г/100г)')),
                ('fat_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жир (г/100г)')),
                ('carbs_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Углеводы (г/100г)')),
                ('fiber_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Клетчатка (г/100г)')),
                ('ash_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Зола (г/100г)')),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Влажность (%)')),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Ингредиенты')),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Аллергены')),
                ('health_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Показания по здоровью')),
                ('age_min_months', models.IntegerField(blank=True, null=True, verbose_name='Мин. возраст (мес)')),
                ('age_max_months', models.IntegerField(blank=True, null=True, verbose_name='Макс. возраст (мес)')),
            ],
            options={
                'verbose_name': 'Детали корма',
                'verbose_name_plural': 'Детали кормов',
                'db_table': 'shop_food_details',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_regular', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая цена')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена со скидкой')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Записано')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'db_table': 'shop_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('similar', 'Похожие товары'), ('complementary', 'Сопутствующие'), ('upsell', 'Более дорогая альтернатива'), ('cross_sell', 'Перекрёстные продажи')], max_length=20, verbose_name='Тип связи')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес связи')),
                ('is_auto', models.BooleanField(default=False, help_text='Сгенерирована алгоритмом или вручную', verbose_name='Автоматическая')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Связь товаров',
                'verbose_name_plural': 'Связи товаров',
                'db_table': 'shop_product_relations',
                'ordering': ['-score', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, verbose_name='Описание для пользователя')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма'), ('free_shipping', 'Бесплатная доставка')], default='percent', max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Размер скидки')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная сумма заказа')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимальная сумма скидки')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Максимум использований')),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='Максимум на пользователя')),
                ('uses_count', models.IntegerField(default=0, verbose_name='Использовано раз')),
                ('applies_to', models.CharField(choices=[('all', 'Вся корзина'), ('category', 'Категория'), ('brand', 'Бренд'), ('product', 'Конкретный товар')], default='all', max_length=20, verbose_name='Применяется к')),
                ('target_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='ID категорий/брендов/товаров', size=None, verbose_name='ID целей')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'shop_promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма скидки')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'db_table': 'shop_promotion_usages',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'shop_wishlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='shop_brands_externa_cf5c7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='shop_catego_externa_b50582_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsku',
            name='idx_skus_external',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='external_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_column='external_id', null=True, unique=True, verbose_name='ID внешнего источника'),
        ),
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_column='external_id', help_text='ID категории из внешнего API', null=True, unique=True, verbose_name='ID внешнего источника'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_column='external_id', help_text='ID товара из внешнего API', null=True, unique=True, verbose_name='ID внешнего источника'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='external_id',
            field=models.BigIntegerField(blank=True, db_column='external_id', null=True, unique=True, verbose_name='ID SKU внешнего источника'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['external_id'], name='idx_brand_external'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['external_id'], name='idx_cat_external'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['external_id'], name='idx_skus_external'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='shop.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='shop.promotion', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='shop.product', verbose_name='Связанный товар'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shop.productsku', verbose_name='Вариант товара'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productrelation',
            unique_together={('product', 'related_product', 'relation_type')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['variant', '-recorded_at'], name='shop_price__variant_91c66a_idx'),
        ),
    ]
