# Generated by Django 4.2.8 on 2026-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shop_v2_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Код для фильтрации: food.dry, care.shampoos, walk.collars', max_length=100, null=True, unique=True, verbose_name='Технический код'),
        ),
    ]
