# Generated by Django 5.1.5 on 2026-03-19 17:30

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_add_shareable_wishlist'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_animal_50c403_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_animal_0efe76_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_vendor_8596a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_price_fe467e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_available',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_in_stock',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_popularity',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_newest',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_discount',
        ),
        migrations.AlterField(
            model_name='shareablewishlist',
            name='share_token',
            field=models.CharField(default=apps.shop.models._default_share_token, editable=False, max_length=64, unique=True, verbose_name='Токен для шаринга'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='shop_produc_product_06d701_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['variant'], name='shop_produc_variant_00dee4_idx'),
        ),
    ]
