# Generated by Django 5.1.5 on 2026-06-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_foodrecipe_supplierrawitem'),
        ('shop', '0028_remove_product_products_animal_50c403_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pets.foodrecipe', verbose_name='Рецепт корма (база питания)'),
        ),
    ]
