# Generated by Django 5.1.5 on 2026-06-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0030_link_rawitems_to_supplier'),
        ('shop', '0029_product_food_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pets.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_skus', to='pets.supplieroffer', verbose_name='Оффер поставщика'),
        ),
    ]
