# Generated by Django 5.1.5 on 2026-06-30 18:16

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Можно оставить пустым — сгенерируется из заголовка.', max_length=220, unique=True, verbose_name='Slug (URL)')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('meetup', 'Сходка/встреча'), ('exhibition', 'Выставка'), ('webinar', 'Вебинар'), ('workshop', 'Мастер-класс'), ('lecture', 'Лекция'), ('other', 'Другое')], db_index=True, default='meetup', max_length=20, verbose_name='Тип')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='Обложка (URL)')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('online_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка (онлайн)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=12, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Можно оставить пустым — сгенерируется из заголовка.', max_length=220, unique=True, verbose_name='Slug (URL)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Анонс')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='Обложка (URL)')),
                ('category', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Категория')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=12, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='events.event', verbose_name='Связанное мероприятие')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_at'], name='events_status_eb474e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'status'], name='events_event_t_e1f6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['status', 'published_at'], name='news_posts_status_cc9aab_idx'),
        ),
    ]
