# Generated by Django 5.1.5 on 2026-06-30 19:10

import apps.events.models
import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscriptionToken',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, default=apps.events.models._generate_feed_key, max_length=64, unique=True, verbose_name='Ключ подписки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен подписки на календарь',
                'verbose_name_plural': 'Токены подписки на календарь',
                'db_table': 'calendar_subscription_tokens',
            },
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='events.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранённое мероприятие',
                'verbose_name_plural': 'Сохранённые мероприятия',
                'db_table': 'saved_events',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
